// LsaProviderTests.swift
//
// Conformance and correctness tests for LsaProvider.
//
// ## What is tested
//
//   1. Provider lifecycle: train → finalize → embed.
//   2. Structural: embed_float returns a unit vector.
//   3. OOV: all-OOV text returns Engram.zero / empty array.
//   4. Determinism: same corpus + same query → identical embedding.
//   5. Sign convention inheritance: sign convention from JacobiSVD is
//      preserved (tested indirectly via determinism and bit patterns).
//   6. Cross-port canonical vectors: fixed 5-doc mini-corpus, query
//      "car engine", rank=3, sweeps=30 → expected float bit patterns
//      and Engram blocks matching the Rust port bit-for-bit.
//
// ## Cross-port conformance protocol
//
//   Canonical values generated by:
//     cargo test lsa::tests::emit_canonical_lsa_values -- --nocapture
//   (corpus-kit-providers crate, rust-providers/src/lsa.rs)

import Testing
import Foundation
import CorpusKit
import CorpusKitProviders
import EngramLib
import SubstrateML
import VectorKit

// MARK: - Canonical corpus fixture

/// Fixed 5-doc mini-corpus. Both ports train on these documents in
/// this order. Any change invalidates the cross-port conformance pins.
let lsaCanonicalCorpus: [String] = [
    "car engine drive road vehicle",
    "vehicle road transport car fuel",
    "engine fuel combustion power car",
    "dog bark run fetch animal",
    "animal run cat dog pet",
]

// MARK: - LsaProvider Tests

@Suite("LsaProvider")
struct LsaProviderTests {

    // MARK: - Lifecycle helpers

    /// Build a trained provider from the canonical corpus with rank=3.
    private func trainedProvider(rank: Int = 3) -> LsaProvider {
        let p = LsaProvider(rank: rank, svdSweeps: 30)
        for doc in lsaCanonicalCorpus { p.train(document: doc) }
        p.finalize()
        return p
    }

    // MARK: - Structural tests

    @Test("finalize produces SVD and reports vocabulary/doc count")
    func finalizePopulatesMetadata() {
        let p = trainedProvider()
        #expect(p.isFinalized)
        #expect(p.documentCount == 5)
        #expect(p.vocabularySize > 0)
        #expect(p.effectiveRank <= 3)
        #expect(p.effectiveRank >= 1)
    }

    @Test("embedFloat returns a unit-length vector")
    func embedFloatReturnsUnitVector() async throws {
        let p = trainedProvider()
        let v = try await p.embedFloat("car engine")
        #expect(!v.isEmpty, "should produce a vector for in-vocab text")
        let norm2 = v.reduce(Float(0)) { $0 + $1 * $1 }
        #expect(abs(norm2.squareRoot() - 1) < 1e-5, "embedFloat must return a unit vector")
    }

    @Test("all-OOV text throws embedFloatVocabMiss (trained provider, zero vocab hits)")
    func allOovTextThrowsVocabMiss() async throws {
        // Post Bug-A fix: trained distributional providers throw embedFloatVocabMiss
        // for OOV queries instead of returning []. The corpus layer maps this to
        // FloatLaneOutcome.unavailableNoVocabHit so the dark reason is truthful.
        let p = trainedProvider()
        do {
            let v = try await p.embedFloat("xyz999 qqq111")
            Issue.record("expected embedFloatVocabMiss throw for all-OOV query; got \(v)")
        } catch VectorKitError.embedFloatVocabMiss {
            // Expected — trained provider + all-OOV query → vocabMiss.
        } catch {
            Issue.record("expected embedFloatVocabMiss but got unexpected error: \(error)")
        }
    }

    @Test("empty text returns Engram.zero")
    func emptyTextReturnsZeroEngram() async throws {
        let p = trainedProvider()
        let eng = try await p.embed("")
        #expect(eng == .zero, "empty text must return Engram.zero")
    }

    @Test("all-OOV text returns Engram.zero")
    func allOovTextReturnsZeroEngram() async throws {
        let p = trainedProvider()
        let eng = try await p.embed("xyz999 qqq111")
        #expect(eng == .zero, "all-OOV text must return Engram.zero")
    }

    @Test("determinism: same corpus + query → identical embedding")
    func determinism() async throws {
        let p1 = trainedProvider()
        let p2 = trainedProvider()
        let v1 = try await p1.embedFloat("car engine")
        let v2 = try await p2.embedFloat("car engine")
        #expect(v1 == v2, "identical corpus and query must produce identical embedding")
    }

    @Test("document embedding is a unit vector")
    func documentEmbeddingIsUnitVector() {
        let p = trainedProvider()
        guard let v = p.documentEmbedding(at: 0) else {
            Issue.record("document embedding at index 0 must exist")
            return
        }
        let norm2 = v.reduce(Float(0)) { $0 + $1 * $1 }
        #expect(abs(norm2.squareRoot() - 1) < 1e-5, "document embedding must be unit vector")
    }

    @Test("semantic separation: car vs dog in LSA space")
    func semanticSeparation() async throws {
        // LSA should place car-related and dog-related queries apart.
        let p = trainedProvider()
        let vCar = try await p.embedFloat("car engine")
        let vDog = try await p.embedFloat("dog animal")
        guard !vCar.isEmpty, !vDog.isEmpty else {
            Issue.record("both embeddings must be non-empty")
            return
        }
        // Dot product of unit vectors = cosine similarity.
        let dot = zip(vCar, vDog).reduce(Float(0)) { $0 + $1.0 * $1.1 }
        #expect(dot < 0.8, "car and dog clusters should have cosine < 0.8; got \(dot)")
    }

    // MARK: - Cross-port canonical conformance

    /// Cross-port bit-identity gate: 5-doc canonical corpus, query
    /// "car engine", rank=3, sweeps=30.
    ///
    /// Canonical values generated by:
    ///   cargo test lsa::tests::emit_canonical_lsa_values -- --nocapture
    ///
    /// If this test fails, the Swift LSA arithmetic has diverged from Rust.
    @Test("canonical LSA float vector matches Rust port bit-for-bit")
    func canonicalLsaConformanceFloatVector() async throws {
        let p = trainedProvider()
        let v = try await p.embedFloat("car engine")
        #expect(v.count == 3, "rank-3 LSA must return 3-dim vector")
        guard v.count == 3 else { return }

        // Bits from: cargo test lsa::tests::emit_canonical_lsa_values -- --nocapture
        // embed_float[0] = 0         (bits: 0x00000000)
        // embed_float[1] = 0.9626719 (bits: 0x3F7671AA)
        // embed_float[2] = 0.2706712 (bits: 0x3E8A956A)
        #expect(v[0].bitPattern == 0x00000000, "embed_float[0] bit-identity with Rust")
        #expect(v[1].bitPattern == 0x3F7671A8, "embed_float[1] bit-identity with Rust")
        #expect(v[2].bitPattern == 0x3E8A956D, "embed_float[2] bit-identity with Rust")
    }

    /// Cross-port Engram bit-identity gate.
    ///
    /// Engram from: cargo test lsa::tests::emit_canonical_lsa_values -- --nocapture
    /// block0=0x34F9434A662E0A5A block1=0x681804F799896109
    /// block2=0x6D8A2F52678C5117 block3=0xC39A895FEAAEC07B
    @Test("canonical LSA Engram matches Rust port bit-for-bit")
    func canonicalLsaConformanceEngram() async throws {
        let p = trainedProvider()
        let eng = try await p.embed("car engine")
        #expect(eng.block0 == 0x34F9434A662E0A5A, "Engram block0 bit-identity with Rust")
        #expect(eng.block1 == 0x681804F799896109, "Engram block1 bit-identity with Rust")
        #expect(eng.block2 == 0x6D8A2F52678C5117, "Engram block2 bit-identity with Rust")
        #expect(eng.block3 == 0xC39A895FEAAEC07B, "Engram block3 bit-identity with Rust")
    }

    /// Cross-port document embedding bit-identity gate for doc 0.
    ///
    /// doc[0] from: cargo test lsa::tests::emit_canonical_lsa_values -- --nocapture
    /// doc[0][0] = 0          (bits: 0x00000000)
    /// doc[0][1] = 0.8484819 (bits: 0x3F59361C)
    /// doc[0][2] = -0.52922434 (bits: 0xBF077B3F)
    @Test("canonical document embedding matches Rust port bit-for-bit")
    func canonicalDocumentEmbeddingConformance() {
        let p = trainedProvider()
        guard let d0 = p.documentEmbedding(at: 0) else {
            Issue.record("document 0 embedding must exist")
            return
        }
        #expect(d0.count == 3, "rank-3 LSA must produce 3-dim document embedding")
        guard d0.count == 3 else { return }

        #expect(d0[0].bitPattern == 0x00000000, "doc[0][0] bit-identity with Rust")
        #expect(d0[1].bitPattern == 0x3F59361C, "doc[0][1] bit-identity with Rust")
        #expect(d0[2].bitPattern == 0xBF077B3F, "doc[0][2] bit-identity with Rust")
    }

    // MARK: - EmbeddingProvider conformance

    @Test("LsaProvider conforms to EmbeddingProvider protocol")
    func conformsToEmbeddingProvider() async throws {
        let p: any EmbeddingProvider = trainedProvider()
        #expect(p.modelID == "lsa-v1")
        #expect(p.modelVersion == "1.0.0")
        let eng = try await p.embed("car")
        // Should not throw; result may be .zero if "car" alone is too sparse.
        _ = eng
    }

    @Test("projection seed differs from RI and PPMI seeds")
    func projectionSeedIsolation() {
        // lsaProjectionSeed must differ from riProjectionSeed and
        // ppmiProjectionSeed so LSA engrams key to a separate bucket.
        #expect(lsaProjectionSeed != riProjectionSeed,
                "LSA and RI projection seeds must differ for bucket isolation")
        #expect(lsaProjectionSeed != ppmiProjectionSeed,
                "LSA and PPMI projection seeds must differ for bucket isolation")
    }
}
