// NmfProviderTests.swift
//
// Conformance and correctness tests for NmfProvider.
//
// ## What is tested
//
//   1. Provider lifecycle: train → finalize → embed.
//   2. Structural: embedFloat returns a unit vector.
//   3. OOV: all-OOV text returns Engram.zero / empty array.
//   4. Determinism: same corpus + same query → identical embedding.
//   5. Document embedding: finalize pre-computes unit-vector doc embeddings.
//   6. Cross-port canonical vectors: fixed 5-doc mini-corpus, query
//      "car engine", rank=3, maxIterations=100, seed=0xDEADBEEFCAFEBABE
//      → expected float bit patterns and Engram blocks matching the
//      Rust port bit-for-bit.
//   7. EmbeddingModel enum: .nmf case is wired and selectable.
//
// ## Cross-port conformance protocol
//
//   Canonical values generated by:
//     cargo test nmf_provider::tests::emit_canonical_nmf_values -- --nocapture
//   (corpus-kit-providers crate, rust-providers/src/nmf_provider.rs)

import Testing
import Foundation
import CorpusKit
import CorpusKitProviders
import EngramLib
import SubstrateML
import VectorKit

// MARK: - Canonical corpus fixture

/// Fixed 5-doc mini-corpus. Both ports train on these documents in
/// this order. Any change invalidates the cross-port conformance pins.
let nmfCanonicalCorpus: [String] = [
    "car engine drive road vehicle",
    "vehicle road transport car fuel",
    "engine fuel combustion power car",
    "dog bark run fetch animal",
    "animal run cat dog pet",
]

// MARK: - NmfProvider Tests

@Suite("NmfProvider")
struct NmfProviderTests {

    // MARK: - Lifecycle helpers

    /// Build a trained provider from the canonical corpus with rank=3.
    private func trainedProvider(rank: Int = 3) -> NmfProvider {
        let p = NmfProvider(rank: rank)
        for doc in nmfCanonicalCorpus { p.train(document: doc) }
        p.finalize()
        return p
    }

    // MARK: - Structural tests

    @Test("finalize produces NMF and reports vocabulary/doc count")
    func finalizePopulatesMetadata() {
        let p = trainedProvider()
        #expect(p.isFinalized)
        #expect(p.documentCount == 5)
        #expect(p.vocabularySize > 0)
        #expect(p.effectiveRank <= 3)
        #expect(p.effectiveRank >= 1)
    }

    @Test("embedFloat returns a unit-length vector")
    func embedFloatReturnsUnitVector() async throws {
        let p = trainedProvider()
        let v = try await p.embedFloat("car engine")
        #expect(!v.isEmpty, "should produce a vector for in-vocab text")
        let norm2 = v.reduce(Float(0)) { $0 + $1 * $1 }
        #expect(abs(norm2.squareRoot() - 1) < 1e-5, "embedFloat must return a unit vector; norm=\(norm2.squareRoot())")
    }

    @Test("all-OOV text throws embedFloatVocabMiss (trained provider, zero vocab hits)")
    func allOovTextThrowsVocabMiss() async throws {
        // Post Bug-A fix: trained distributional providers throw embedFloatVocabMiss
        // for OOV queries instead of returning []. The corpus layer maps this to
        // FloatLaneOutcome.unavailableNoVocabHit so the dark reason is truthful.
        let p = trainedProvider()
        do {
            let v = try await p.embedFloat("xyz999 qqq111")
            Issue.record("expected embedFloatVocabMiss throw for all-OOV query; got \(v)")
        } catch VectorKitError.embedFloatVocabMiss {
            // Expected — trained provider + all-OOV query → vocabMiss.
        } catch {
            Issue.record("expected embedFloatVocabMiss but got unexpected error: \(error)")
        }
    }

    @Test("empty text returns Engram.zero")
    func emptyTextReturnsZeroEngram() async throws {
        let p = trainedProvider()
        let eng = try await p.embed("")
        #expect(eng == .zero, "empty text must return Engram.zero")
    }

    @Test("all-OOV text returns Engram.zero")
    func allOovTextReturnsZeroEngram() async throws {
        let p = trainedProvider()
        let eng = try await p.embed("xyz999 qqq111")
        #expect(eng == .zero, "all-OOV text must return Engram.zero")
    }

    @Test("determinism: same corpus + query → identical embedding")
    func determinism() async throws {
        let p1 = trainedProvider()
        let p2 = trainedProvider()
        let v1 = try await p1.embedFloat("car engine")
        let v2 = try await p2.embedFloat("car engine")
        #expect(v1 == v2, "identical corpus and query must produce identical embedding")
    }

    @Test("document embedding is a unit vector")
    func documentEmbeddingIsUnitVector() {
        let p = trainedProvider()
        guard let v = p.documentEmbedding(at: 0) else {
            Issue.record("document embedding at index 0 must exist")
            return
        }
        let norm2 = v.reduce(Float(0)) { $0 + $1 * $1 }
        #expect(abs(norm2.squareRoot() - 1) < 1e-5, "document embedding must be unit vector; norm=\(norm2.squareRoot())")
    }

    @Test("semantic separation: car vs dog in NMF space")
    func semanticSeparation() async throws {
        // NMF should place car-related and dog-related queries apart.
        let p = trainedProvider()
        let vCar = try await p.embedFloat("car engine")
        let vDog = try await p.embedFloat("dog animal")
        guard !vCar.isEmpty, !vDog.isEmpty else {
            Issue.record("both embeddings must be non-empty")
            return
        }
        // Dot product of unit vectors = cosine similarity.
        let dot = zip(vCar, vDog).reduce(Float(0)) { $0 + $1.0 * $1.1 }
        // NMF with only 3 latent factors on 5 docs will separate the two
        // semantic clusters; cosine should be < 0.9 for meaningful separation.
        #expect(dot < 0.9, "car and dog clusters should have cosine < 0.9; got \(dot)")
    }

    // MARK: - Cross-port canonical conformance

    /// Print canonical bit patterns for cross-port conformance pinning.
    /// Run with: swift test --filter "NmfProvider/emitCanonicalNmfValues"
    @Test("emitCanonicalNmfValues")
    func emitCanonicalNmfValues() async throws {
        let p = trainedProvider()
        let v = try await p.embedFloat("car engine")
        print("=== CANONICAL NMF EMBEDDING VALUES ===")
        print("Query: 'car engine', corpus: 5-doc canonical, rank=3, iterations=100, seed=0xDEADBEEFCAFEBABE")
        for (i, val) in v.enumerated() {
            print("  embed_float[\(i)] = \(val) (bits: 0x\(String(val.bitPattern, radix: 16, uppercase: true).uppercased().leftPad(toLength: 8, with: "0")))")
        }
        let eng = try await p.embed("car engine")
        print("Engram: block0=0x\(String(eng.block0, radix: 16, uppercase: true)) block1=0x\(String(eng.block1, radix: 16, uppercase: true)) block2=0x\(String(eng.block2, radix: 16, uppercase: true)) block3=0x\(String(eng.block3, radix: 16, uppercase: true))")
        if let d0 = p.documentEmbedding(at: 0) {
            for (i, val) in d0.enumerated() {
                print("  doc[0][\(i)] = \(val) (bits: 0x\(String(val.bitPattern, radix: 16, uppercase: true).uppercased().leftPad(toLength: 8, with: "0")))")
            }
        }
        print("=== END CANONICAL NMF VALUES ===")
    }

    /// Cross-port bit-identity gate: 5-doc canonical corpus, query
    /// "car engine", rank=3, maxIterations=100, seed=0xDEADBEEFCAFEBABE.
    ///
    /// Canonical values generated by:
    ///   cargo test nmf_provider::tests::emit_canonical_nmf_values -- --nocapture
    ///
    /// Confirmed bit-identical between Swift and Rust. If this test fails,
    /// the Swift NMF arithmetic has diverged from Rust.
    @Test("canonical NMF float vector matches Rust port bit-for-bit")
    func canonicalNmfConformanceFloatVector() async throws {
        let p = trainedProvider()
        let v = try await p.embedFloat("car engine")
        #expect(v.count == 3, "rank-3 NMF must return 3-dim vector")
        guard v.count == 3 else { return }

        // Bits from: cargo test nmf_provider::tests::emit_canonical_nmf_values -- --nocapture
        // embed_float[0] = 0.84187937 (bits: 0x3F578568)
        // embed_float[1] = 0.53966576 (bits: 0x3F0A2789)
        // embed_float[2] = 0          (bits: 0x00000000)
        #expect(v[0].bitPattern == 0x3F578568, "embed_float[0] bit-identity with Rust")
        #expect(v[1].bitPattern == 0x3F0A2789, "embed_float[1] bit-identity with Rust")
        #expect(v[2].bitPattern == 0x00000000, "embed_float[2] bit-identity with Rust")
    }

    /// Cross-port Engram bit-identity gate.
    ///
    /// Engram from: cargo test nmf_provider::tests::emit_canonical_nmf_values -- --nocapture
    /// block0=0xB7AB5528EF12D061 block1=0xC452A7DEFE999697
    /// block2=0x325CFC0C6D14A93F block3=0xA1591A2717EBC02B
    @Test("canonical NMF Engram matches Rust port bit-for-bit")
    func canonicalNmfConformanceEngram() async throws {
        let p = trainedProvider()
        let eng = try await p.embed("car engine")
        #expect(eng.block0 == 0xB7AB5528EF12D061, "Engram block0 bit-identity with Rust")
        #expect(eng.block1 == 0xC452A7DEFE999697, "Engram block1 bit-identity with Rust")
        #expect(eng.block2 == 0x325CFC0C6D14A93F, "Engram block2 bit-identity with Rust")
        #expect(eng.block3 == 0xA1591A2717EBC02B, "Engram block3 bit-identity with Rust")
    }

    /// Cross-port document embedding bit-identity gate for doc 0.
    ///
    /// doc[0] from: cargo test nmf_provider::tests::emit_canonical_nmf_values -- --nocapture
    /// doc[0][0] = 0.015156989 (bits: 0x3C785505)
    /// doc[0][1] = 0.9998851   (bits: 0x3F7FF878)
    /// doc[0][2] = 0           (bits: 0x00000000)
    @Test("canonical document embedding matches Rust port bit-for-bit")
    func canonicalDocumentEmbeddingConformance() {
        let p = trainedProvider()
        guard let d0 = p.documentEmbedding(at: 0) else {
            Issue.record("document 0 embedding must exist")
            return
        }
        #expect(d0.count == 3, "rank-3 NMF must produce 3-dim document embedding")
        guard d0.count == 3 else { return }

        #expect(d0[0].bitPattern == 0x3C785505, "doc[0][0] bit-identity with Rust")
        #expect(d0[1].bitPattern == 0x3F7FF878, "doc[0][1] bit-identity with Rust")
        #expect(d0[2].bitPattern == 0x00000000, "doc[0][2] bit-identity with Rust")
    }

    // MARK: - EmbeddingModel enum wiring

    @Test("EmbeddingModel.nmf case is wired and reachable")
    func embeddingModelNmfCaseWired() {
        // Build a trained NmfProvider and confirm it can be passed as .nmf
        // to EmbeddingModel. The switch exhaustiveness in CorpusKit.swift
        // enforces that .nmf is wired in makeProvider().
        let provider = trainedProvider()
        // Verify the provider protocol conformance.
        let ep: any EmbeddingProvider = provider
        #expect(ep.modelID == "nmf-v1")
        #expect(ep.modelVersion == "1.0.0")
    }

    @Test("projection seed differs from LSA, RI, and PPMI seeds")
    func projectionSeedIsolation() {
        #expect(nmfProjectionSeed != lsaProjectionSeed,
                "NMF and LSA projection seeds must differ for bucket isolation")
        #expect(nmfProjectionSeed != riProjectionSeed,
                "NMF and RI projection seeds must differ for bucket isolation")
        #expect(nmfProjectionSeed != ppmiProjectionSeed,
                "NMF and PPMI projection seeds must differ for bucket isolation")
    }
}

// MARK: - String left-pad helper (local to test file)

private extension String {
    func leftPad(toLength length: Int, with pad: Character) -> String {
        guard count < length else { return self }
        return String(repeating: pad, count: length - count) + self
    }
}
