//! Drawer struct. Ports `Drawer.swift`.
//!
//! A drawer is what callers ingest and what the search pipeline returns.
//! The `content` field is preserved unchanged — no truncation, no
//! normalization — because the verbatim-first pillar of MemPalace
//! requires that retrieval surface exactly what was filed.
//!
//! Every drawer belongs to a room node in the estate's containment tree
//! (ADR-017). The `parent_node_id` field is the UUID of the room node.
//! Display names (wing, room) are resolved via `DrawerStore::resolve_node_names`
//! when needed — they are not stored on the Drawer struct.
//!
//! `embedding_model_id` is present from day one even though no
//! embeddings are generated in this mission. The modelID-tagging rule
//! (one of the architectural constraints of Loci Mode) requires every
//! drawer to carry the identifier of the embedder that produced its
//! vector, so vectors generated by different models can never be
//! compared accidentally.
//!
//! `tombstoned_at` and `removed_by_batch` belong to the soft-delete
//! machinery added in Rev 2.0. They are present on the schema from
//! Rev 1.0 so the layout never needs to migrate.
//!
//! ## Swift-to-Rust shape changes
//!
//! - `Date filedAt` → `i64 filed_at` (epoch seconds). Matches the
//!   leaf-type convention documented in `audit_types.rs` / `manifest.rs`:
//!   the Rust port stores timestamps as i64 epoch seconds and the
//!   persistence-kit `TypedValue::Timestamp(i64)` carries them on the wire.
//!   The Swift port uses `Date` because the storage layer there hands
//!   back `Date`; both legs agree on the canonical wire shape (ISO8601
//!   in SQLite).
//! - `UUID lineageID` → `uuid::Uuid lineage_id`. Same value semantics.

use crate::provenance::{
    CaptureChannel, Channel, Confidence, Confirmation, EnrichmentStatus, Sensitivity, SourceType,
};
use uuid::Uuid;
// ─────────────────────────────────────────────────────────────────
// DO NOT REIMPLEMENT SUBSTRATE MATH.
//
// The substrate publishes conformance-gated, byte-identical
// Swift+Rust implementations of every primitive listed in
// docs/engineering/HARNESS_REFERENCE.md. If you
// need a SimHash, Hamming distance, OR-reduce, Fingerprint256 op,
// HammingNN top-K, HLC tick, AuditGate admit, MatrixDecay, audit-
// log fold, Bradley-Terry update, NMF, FFT, eigenvalue centrality,
// or any other substrate primitive, it's already in substrate-types,
// substrate-kernel, or substrate-ml. CI catches drift four ways.
// See packages/libs/Substrate{Types,Kernel,ML}/AGENTS.md.
// ─────────────────────────────────────────────────────────────────
use substrate_kernel::bit_field;

/// A unit of verbatim content stored in the MemPalace surface.
///
/// Mirrors `Drawer` in `Drawer.swift` field-for-field. The three Int64
/// bitmaps (`provenance`, `adjective_bitmap`, `operational_bitmap`)
/// carry the typed-axis state defined in `provenance.rs`,
/// `adjectives.rs`, and `drawer_operational.rs` respectively. Accessors
/// for the provenance axes live on this struct below; accessors for the
/// operational axes live in `drawer_operational.rs` (split mirrors the
/// Swift file split).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Drawer {
    /// Stable identifier supplied by the caller. Defaults to a fresh
    /// UUID string when omitted; callers ingesting previously-known
    /// content should supply a deterministic id.
    pub id: String,

    /// Lineage identifier shared across all versions of a single
    /// content lineage per spec § 5.10. Always present, never None.
    /// When the caller omits this argument the substrate generates a
    /// fresh UUID so each new drawer is its own lineage by default.
    pub lineage_id: Uuid,

    /// The content as filed. Verbatim, no transformation.
    pub content: String,

    /// UUID of the room node that contains this drawer (ADR-017 §3).
    /// Foreign key to nodes.id; the referenced node has depth=2
    /// (room level) in the estate containment tree.
    pub parent_node_id: String,

    /// Optional path of the file this drawer was ingested from.
    pub source_file: Option<String>,

    /// Optional position of this drawer inside its source. Used by the
    /// directory walker to dedup re-ingest cycles.
    pub chunk_index: Option<i64>,

    /// Name of the agent or process that filed this drawer.
    pub added_by: String,

    /// When the drawer was added. Epoch seconds in the Rust port; the
    /// SQLite column stores ISO8601 TEXT per the fleet rule.
    pub filed_at: i64,

    /// When the content happened or was authored in the world. For
    /// streaming capture this equals `filed_at`. For bulk historical
    /// ingestion callers supply the original authorship date. The
    /// fingerprint's capture-week bucket keys off this field, not
    /// `filed_at` (ING-01, two-clock ingest). Epoch seconds. Always
    /// non-optional: resolved eagerly to `filed_at` at construction or
    /// decode so the struct never carries an absent value. Mirrors Swift
    /// `Drawer.eventTime: Date` (non-optional, folded to `filedAt` on
    /// decode). Stored as TEXT ISO8601 at the SQLite boundary per the
    /// fleet date-storage rule; the column is nullable to support legacy
    /// rows pre-dating the column, but the in-struct type is not.
    pub event_time: i64,

    /// Identifier of the embedding model that produced (or will
    /// produce) the vector for this drawer.
    pub embedding_model_id: String,

    /// When this drawer was tombstoned, if it has been. Written by
    /// expunge/tombstone paths; `None` while the drawer is active.
    pub tombstoned_at: Option<i64>,

    /// Batch identifier used for receipt-based rollback of a tombstone.
    /// Reserved for the Rev 2.0 soft-delete workflow.
    pub removed_by_batch: Option<String>,

    /// Provenance bitmap encoding source type, channel, provenance capture
    /// channel, confirmation, confidence, sensitivity, and enrichment
    /// status per Q1_DECISION_PROVENANCE_BITMAP.md. See `provenance.rs`
    /// for the axis enums and the accessor methods below for type-safe
    /// decoding.
    pub provenance: i64,

    /// Adjective bitmap encoding state, sensitivity, exportability, and
    /// trust per spec § 5.5. See `adjectives.rs` for the four axis enums.
    pub adjective_bitmap: i64,

    /// Operational bitmap encoding capture channel, content kind,
    /// feature flags, the lineage-clustering bit, and the
    /// state-extension flag per spec § 5.6. See `drawer_operational.rs`
    /// for the enums, the feature-flag bitset constants, and the accessor
    /// methods.
    pub operational_bitmap: i64,

    /// UDC (Universal Decimal Classification) code locating this
    /// drawer in the depth axis of the universal lattice per spec § 5.8
    /// and I-5. Empty string means "no anchor declared" — the no-anchor
    /// sentinel is empty rather than None so the SQLite column can be
    /// `NOT NULL DEFAULT ''`.
    pub udc_code: String,

    /// Optional UDC facet expression refining `udc_code`. None means
    /// "no facet expression" — distinguishes "no facets recorded" from
    /// "facet expression intentionally blank."
    pub udc_facets: Option<String>,

    /// Primary Wikidata Q-ID anchoring this drawer to a stable concept
    /// identifier (e.g., `Q11351` for "organic chemistry").
    pub wikidata_qid: Option<String>,

    /// Comma-separated secondary Wikidata Q-IDs for drawers whose
    /// content spans multiple concepts. Stored as a single TEXT column
    /// rather than a join table because the lattice anchor is read in
    /// every retrieval path. Format is the comma-separated Q-ID list
    /// with no internal whitespace.
    pub wikidata_qids_secondary: Option<String>,
}

impl Drawer {
    /// Designated constructor with the minimum required fields. Other
    /// fields default to their Rev-1.0 zero values; callers populate
    /// what they need by assignment. Mirrors the Swift designated
    /// initializer's parameter set.
    pub fn new(
        id: impl Into<String>,
        content: impl Into<String>,
        parent_node_id: impl Into<String>,
        added_by: impl Into<String>,
        filed_at: i64,
        embedding_model_id: impl Into<String>,
    ) -> Self {
        Drawer {
            id: id.into(),
            lineage_id: Uuid::new_v4(),
            content: content.into(),
            parent_node_id: parent_node_id.into(),
            source_file: None,
            chunk_index: None,
            added_by: added_by.into(),
            filed_at,
            // Eager resolution: streaming capture → event_time == filed_at by
            // default. Callers doing bulk historical ingest assign event_time
            // immediately after construction; the estate_verbs capture path
            // always resolves from the CaptureFrame before calling add_drawer.
            event_time: filed_at,
            embedding_model_id: embedding_model_id.into(),
            tombstoned_at: None,
            removed_by_batch: None,
            provenance: 0,
            adjective_bitmap: 0,
            operational_bitmap: 0,
            udc_code: String::new(),
            udc_facets: None,
            wikidata_qid: None,
            wikidata_qids_secondary: None,
        }
    }
}

// MARK: - Adjective accessors (cookbook §2.3)

impl Drawer {
    /// True when this row's graph contribution has been disturbed
    /// (by redact/expunge, mass-mutation, lineage rewrite, or any
    /// other operation that invalidates downstream relationships)
    /// and the dreaming pass has not yet reconciled the affected
    /// neighborhood. Cookbook §2.3 bit 26, F17 cascade (2026-05-27).
    ///
    /// Polarity is *obligation*, not state: true = recalc owed,
    /// false = no recalc owed (either never disturbed or dreaming
    /// has visited since the last disturbance). See cookbook §9.5.1
    /// for the content-vs-graph distinction this flag encodes.
    pub fn dreaming_recalc_required(&self) -> bool {
        // Cookbook §2.3 bit 26 (F17 cascade).
        bit_field::extract_flag(self.adjective_bitmap, 26)
    }

    /// True when a valid integrity seal exists for this row's current
    /// state. Cookbook §2.3 bit 27 (custody cascade, 2026-05-28).
    ///
    /// Polarity: 1 = sealed (higher custody trust), 0 = unsealed (more
    /// recent / emergent). Cached *trust hint* only — the proof is the
    /// seal stored elsewhere; if bit and seal disagree, the seal wins.
    /// Set only by the seal-writing/verifying path: strict stamps 1 at
    /// write; lazy stamps 0 at write and the dreaming pass flips to 1.
    /// Unsealed rows are the dreaming seal queue (`!sealed()`).
    pub fn sealed(&self) -> bool {
        // Cookbook §2.3 bit 27 (custody cascade).
        bit_field::extract_flag(self.adjective_bitmap, 27)
    }
}

// MARK: - Provenance accessors (cookbook §2.5 v0.6)

impl Drawer {
    /// Decode bits 0–5 of `provenance` as a `SourceType`. Returns
    /// `User` for unrecognised raw values (the v0.6 default fallback
    /// per cookbook §2.5).
    pub fn source_type(&self) -> SourceType {
        SourceType::from_raw(bit_field::extract_field(self.provenance, 0, 6))
    }

    /// Decode bits 6–11 of `provenance` as a `Channel`. Returns
    /// `UiTyped` for unrecognised raw values (including reserved-gap
    /// raws 9–14 and 17–63).
    pub fn channel(&self) -> Channel {
        Channel::from_raw(bit_field::extract_field(self.provenance, 6, 6))
    }

    /// Decode bits 12–17 of `provenance` as a `CaptureChannel`.
    /// Mirrors the operational §2.4 capture_channel field per cookbook
    /// §2.5. Returns `Typed` for unrecognised raw values.
    pub fn provenance_capture_channel(&self) -> CaptureChannel {
        CaptureChannel::from_raw(bit_field::extract_field(self.provenance, 12, 6))
    }

    /// Decode bits 18–23 of `provenance` as a `Confirmation`.
    /// Returns `Unconfirmed` for unrecognised raw values so retrieval
    /// filters that exclude unconfirmed content fail closed rather than
    /// open.
    pub fn confirmation(&self) -> Confirmation {
        Confirmation::from_raw(bit_field::extract_field(self.provenance, 18, 6))
    }

    /// Decode bits 24–29 of `provenance` as a `Confidence`. Returns
    /// `Null` for unrecognised raw values (including the scale gaps
    /// between cookbook §2.5 raws 0/16/32/48/56).
    pub fn confidence(&self) -> Confidence {
        Confidence::from_raw(bit_field::extract_field(self.provenance, 24, 6))
    }

    /// Decode bits 30–35 of `provenance` as a `Sensitivity`. Returns
    /// `Normal` for unrecognised raw values, matching the estate-level
    /// default access posture. Mirrors adjective sensitivity raws per
    /// cookbook §2.5.
    pub fn sensitivity(&self) -> Sensitivity {
        Sensitivity::from_raw(bit_field::extract_field(self.provenance, 30, 6))
    }

    /// Decode bits 36–41 of `provenance` as an `EnrichmentStatus`.
    /// Returns `None` for unrecognised raw values. NEW in v0.6.
    pub fn enrichment_status(&self) -> EnrichmentStatus {
        EnrichmentStatus::from_raw(bit_field::extract_field(self.provenance, 36, 6))
    }

    /// True when the drawer has been reviewed and approved by the user
    /// (Confirmation::UserConfirmed exactly). Used by retrieval layers
    /// that only surface user-vetted content for agent action context.
    pub fn is_user_confirmed(&self) -> bool {
        self.confirmation() == Confirmation::UserConfirmed
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Drawer {
        Drawer::new(
            "d1",
            "hello",
            "test-parent",
            "alice",
            1_700_000_000,
            "test-v1",
        )
    }

    #[test]
    fn default_bitmaps_are_zero() {
        let d = sample();
        assert_eq!(d.provenance, 0);
        assert_eq!(d.adjective_bitmap, 0);
        assert_eq!(d.operational_bitmap, 0);
    }

    #[test]
    fn default_udc_code_is_empty_string() {
        // Spec contract: empty string means "no anchor declared". Distinct
        // from None — the SQLite column is NOT NULL DEFAULT ''.
        let d = sample();
        assert_eq!(d.udc_code, "");
        assert!(d.udc_facets.is_none());
        assert!(d.wikidata_qid.is_none());
    }

    #[test]
    fn fresh_lineage_per_construction() {
        let a = sample();
        let b = sample();
        assert_ne!(a.lineage_id, b.lineage_id);
    }

    #[test]
    fn source_type_decodes_bits_0_5_cookbook_2_5() {
        let mut d = sample();
        d.provenance = SourceType::Canonical.raw_value();
        assert_eq!(d.source_type(), SourceType::Canonical);
        // High bits don't leak in.
        d.provenance = SourceType::Ambient.raw_value() | (1 << 50);
        assert_eq!(d.source_type(), SourceType::Ambient);
    }

    #[test]
    fn channel_decodes_bits_6_11_cookbook_2_5() {
        let mut d = sample();
        d.provenance = Channel::McpAgent.raw_value() << 6;
        assert_eq!(d.channel(), Channel::McpAgent);
    }

    #[test]
    fn confirmation_decodes_bits_18_23_cookbook_2_5() {
        let mut d = sample();
        d.provenance = Confirmation::UserConfirmed.raw_value() << 18;
        assert_eq!(d.confirmation(), Confirmation::UserConfirmed);
    }

    #[test]
    fn confidence_decodes_bits_24_29_cookbook_2_5() {
        let mut d = sample();
        d.provenance = Confidence::High.raw_value() << 24;
        assert_eq!(d.confidence(), Confidence::High);
    }

    #[test]
    fn sensitivity_decodes_bits_30_35_cookbook_2_5() {
        let mut d = sample();
        d.provenance = Sensitivity::Restricted.raw_value() << 30;
        assert_eq!(d.sensitivity(), Sensitivity::Restricted);
    }

    #[test]
    fn enrichment_status_decodes_bits_36_41_cookbook_2_5() {
        let mut d = sample();
        d.provenance = EnrichmentStatus::QidCompleted.raw_value() << 36;
        assert_eq!(d.enrichment_status(), EnrichmentStatus::QidCompleted);
    }

    #[test]
    fn is_user_confirmed_only_when_userconfirmed_exactly() {
        let mut d = sample();
        d.provenance = Confirmation::UserConfirmed.raw_value() << 18;
        assert!(d.is_user_confirmed());

        // AutomatedConfirmed/PeerConfirmed/ActuatorConfirmed are NOT user-confirmed.
        d.provenance = Confirmation::AutomatedConfirmed.raw_value() << 18;
        assert!(!d.is_user_confirmed());
        d.provenance = Confirmation::PeerConfirmed.raw_value() << 18;
        assert!(!d.is_user_confirmed());
    }

    #[test]
    fn future_version_raw_values_fail_safe() {
        // Reserved raws must decode to safe fallbacks per cookbook §2.5.
        let mut d = sample();
        d.provenance = 0x3F; // bits 0–5 = 63, reserved SourceType
        assert_eq!(d.source_type(), SourceType::User);
        d.provenance = 0x3F << 18; // bits 18–23 = 63, reserved Confirmation
        assert_eq!(d.confirmation(), Confirmation::Unconfirmed);
    }
}

#[cfg(test)]
mod sealed_bit_tests {
    use substrate_kernel::bit_field;

    #[test]
    fn bit_27_set_means_sealed() {
        let adj = bit_field::write_flag(true, 0, 27);
        assert!(bit_field::extract_flag(adj, 27));
    }

    #[test]
    fn bit_27_clear_means_unsealed() {
        assert!(!bit_field::extract_flag(0, 27));
    }

    #[test]
    fn sealed_independent_of_trust() {
        let adj = bit_field::write_field(3, 0, 18, 6); // canonical
        assert!(
            !bit_field::extract_flag(adj, 27),
            "trust set must not set seal"
        );
        let sealed = bit_field::write_flag(true, adj, 27);
        assert!(bit_field::extract_flag(sealed, 27));
        assert_eq!((sealed >> 18) & 0x3F, 3, "sealing must not disturb trust");
    }

    #[test]
    fn bit_27_does_not_collide_with_bit_26() {
        let only_seal = bit_field::write_flag(true, 0, 27);
        assert!(
            !bit_field::extract_flag(only_seal, 26),
            "27 must not read as 26"
        );
    }
}
