#!/usr/bin/env python3
"""Coordinated release version bump for the CE product.

A release version lives in ~16 hand-maintained sites across three groups
(binary stamps, plugin manifests, embedded installer copies). Bumping them by
hand is how v1.0.31 shipped with three of them still reading 1.0.30. This script
bumps every stamp in one shot, preserving each file's exact byte format (literal
replacement, never re-serialization — the embedded copies must stay byte-identical
to what the packager produces), then runs verify_version.py as the gate.

  python3 scripts/release/bump_version.py 1.0.32
  python3 scripts/release/bump_version.py 1.1.0-beta-04 --date 2026-07-24

It REFUSES to run unless the tree is already consistent at the current version
(verify_version passes first), so it can never compound an existing drift.

It does NOT write the root CHANGELOG.md — those are human-authored release notes,
not a stamp. It prints a reminder to add them.

NOTE (long-term): the plugin manifests and embedded copies are generated by the
EE `tools/moot-packager`. Once the packager stamps the version itself and CE
re-syncs, groups 2 and 3 below become packager-owned and this script narrows to
the binary stamps + orchestration. Until then it maintains all three so CE can
cut a release on its own; verify_version.py is the invariant either way.
"""
from __future__ import annotations
import argparse
import datetime
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

CARGO_TOML = "apps/mootx01/rust/Cargo.toml"
CARGO_LOCK = "apps/mootx01/rust/Cargo.lock"
MOOTMAIN = "apps/mootx01/Sources/mootx01/MootMain.swift"
LIBRS = "apps/mootx01/rust/src/lib.rs"
README = "distribution/plugin/README.md"
PLUGIN_CHANGELOG = "distribution/plugin/CHANGELOG.md"
INSTALL_BUNDLE = "apps/mootx01/rust/src/embedded/install-bundle.json"
EMBEDDED_SWIFT = "apps/mootx01/Sources/MootInstallerCore/Generated/EmbeddedArtifacts.swift"
PLUGIN_MANIFESTS = [
    "distribution/plugin/.claude-plugin/plugin.json",
    "distribution/plugin/.codex-plugin/plugin.json",
    "distribution/plugin/.cursor-plugin/plugin.json",
    "distribution/plugin/.plugin/plugin.json",
    "distribution/plugin/plugin.json",
    "distribution/plugin/gemini-extension.json",
]

VERSION_RE = re.compile(
    r"^\d+\.\d+\.\d+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)


def rd(rel: str) -> str:
    return (ROOT / rel).read_text()


def wr(rel: str, text: str) -> None:
    (ROOT / rel).write_text(text)


def sub_once(rel: str, old: str, new: str, *, required: int = 1) -> int:
    """Literal-replace `old`→`new` in a file; assert an exact occurrence count."""
    text = rd(rel)
    n = text.count(old)
    if n != required:
        raise SystemExit(
            f"bump: {rel}: expected {required} occurrence(s) of {old!r}, found {n}"
        )
    wr(rel, text.replace(old, new))
    return n


def sub_all(rel: str, old: str, new: str) -> int:
    """Literal-replace every `old`→`new`; return count (must be > 0)."""
    text = rd(rel)
    n = text.count(old)
    if n == 0:
        raise SystemExit(f"bump: {rel}: no occurrence of {old!r} to replace")
    wr(rel, text.replace(old, new))
    return n


def current_version() -> str:
    in_pkg = False
    for line in rd(CARGO_TOML).splitlines():
        s = line.strip()
        if s.startswith("["):
            in_pkg = s == "[package]"
        elif in_pkg and s.startswith("version"):
            m = re.search(r'"([^"]+)"', s)
            if m:
                return m.group(1)
    raise SystemExit("bump: could not read current [package] version")


def current_release_date() -> str:
    m = re.search(r'releaseDate\s*=\s*"([^"]+)"', rd(MOOTMAIN))
    if not m:
        raise SystemExit("bump: could not read current releaseDate from MootMain")
    return m.group(1)


def run_verify(version: str) -> int:
    return subprocess.run(
        [sys.executable, str(ROOT / "scripts/release/verify_version.py"), version]
    ).returncode


def main() -> None:
    ap = argparse.ArgumentParser(description="Coordinated CE release version bump.")
    ap.add_argument(
        "new_version",
        help="target SemVer, e.g. 1.0.32 or 1.1.0-beta-03",
    )
    ap.add_argument("--date", help="release date YYYY-MM-DD (default: today)")
    args = ap.parse_args()

    new = args.new_version
    if not VERSION_RE.match(new):
        raise SystemExit(f"bump: {new!r} is not a supported SemVer")
    new_date = args.date or datetime.date.today().isoformat()
    if not re.match(r"^\d{4}-\d{2}-\d{2}$", new_date):
        raise SystemExit(f"bump: {new_date!r} is not an ISO date (YYYY-MM-DD)")

    cur = current_version()
    if cur == new:
        raise SystemExit(f"bump: tree is already at {new}; nothing to do")
    cur_date = current_release_date()

    # Guard: refuse to bump a tree that isn't already consistent at `cur`, so a
    # pre-existing drift can never be compounded (silently left behind).
    print(f"bump: checking tree is consistent at {cur} before bumping…")
    if run_verify(cur) != 0:
        raise SystemExit(
            f"bump: tree is NOT consistent at {cur}; fix the drift first "
            f"(see the ✗ lines above), then re-run."
        )

    print(f"bump: {cur} → {new}  (release date {cur_date} → {new_date})")

    # --- Group 1: binary stamps ---
    sub_once(MOOTMAIN, f'currentVersion = "{cur}"', f'currentVersion = "{new}"')
    sub_once(MOOTMAIN, f'releaseDate = "{cur_date}"', f'releaseDate = "{new_date}"')
    sub_once(LIBRS, f'RELEASE_DATE: &str = "{cur_date}";', f'RELEASE_DATE: &str = "{new_date}";')
    sub_once(CARGO_TOML,
             f'name = "mootx01-cli"\nversion = "{cur}"',
             f'name = "mootx01-cli"\nversion = "{new}"')
    sub_once(CARGO_LOCK,
             f'name = "mootx01-cli"\nversion = "{cur}"',
             f'name = "mootx01-cli"\nversion = "{new}"')

    # --- Group 2: plugin manifests (version value only, format preserved) ---
    for rel in PLUGIN_MANIFESTS:
        sub_once(rel, f'"version" : "{cur}"', f'"version" : "{new}"')
    sub_once(README, f"Version {cur}", f"Version {new}")
    sub_once(PLUGIN_CHANGELOG, f"## [{cur}]", f"## [{new}]")

    # --- Group 3: embedded installer copies (every current-version token) ---
    # All 3-part tokens equal to `cur` in these bundles are current-version
    # fields (per-host plugin.json/README/changelog embedded); IPs and 2-part
    # roadmap tokens don't equal `cur`, so a literal `cur`→`new` is exact. The
    # verify pass below re-checks byte-consistency and that no stray token remains.
    nj = sub_all(INSTALL_BUNDLE, cur, new)
    ns = sub_all(EMBEDDED_SWIFT, cur, new)
    if nj != ns:
        raise SystemExit(
            f"bump: embedded copies disagree on occurrence count "
            f"(install-bundle.json {nj} vs EmbeddedArtifacts.swift {ns}) — inspect before committing"
        )

    print(f"bump: rewrote all stamps. Verifying at {new}…")
    if run_verify(new) != 0:
        raise SystemExit("bump: post-bump verify FAILED — do not commit; inspect the ✗ lines.")

    print(
        f"\nbump: OK — every stamp now reads {new} ({new_date}).\n"
        "Next: add a root CHANGELOG.md entry (human release notes — not stamped by\n"
        "this script), build both legs, then flow develop→candidate→stable and cut\n"
        "the tag LAST on the stable HEAD."
    )


if __name__ == "__main__":
    main()
