//! Cross-port conformance gate for the ratified int8 quantisation policy
//! (ENCODER_RERANK_CONTRACT §4): ../Tests/Fixtures/encoder/int8_vectors.json,
//! generated by gen_int8_vectors.py beside it and asserted by the Swift twin
//! (Int8VecConformanceTests), so both ports are pinned to one file, not to
//! each other.
//!
//! `q` and `scale` must match bit for bit: the inputs are decimals both ports
//! decode to the same f32, so a byte difference is a rounding-mode, clamp, or
//! divisor bug (half-to-even, ÷128, asymmetric range). `dot_query` must agree
//! within 1e-5.

use serde_json::Value;
use std::path::PathBuf;
use substrate_kernel::int8_vec;

fn fixture() -> Value {
    // CARGO_MANIFEST_DIR is SynapseKit/rust/; the fixture lives one level up.
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../Tests/Fixtures/encoder/int8_vectors.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("fixture JSON must parse")
}

fn floats(v: &Value) -> Vec<f32> {
    v.as_array()
        .expect("float array")
        .iter()
        .map(|x| x.as_f64().expect("float") as f32)
        .collect()
}

fn ints(v: &Value) -> Vec<i8> {
    v.as_array()
        .expect("int array")
        .iter()
        .map(|x| x.as_i64().expect("int") as i8)
        .collect()
}

fn check(label: &str, v: &[f32], u: &[f32], expected_q: &[i8], expected_scale: f32, expected_dot: f32) {
    let (q, scale) = int8_vec::quantize(v);
    assert_eq!(q, expected_q, "{label}: q mismatch");
    assert_eq!(
        scale.to_bits(),
        expected_scale.to_bits(),
        "{label}: scale {scale} vs {expected_scale}"
    );
    let dot = int8_vec::dot_query(u, &q, scale);
    assert!(
        (dot - expected_dot).abs() <= 1e-5,
        "{label}: dot {dot} vs {expected_dot}"
    );
}

#[test]
fn every_fixture_vector_quantises_bit_exactly_and_scores_within_tolerance() {
    let root = fixture();
    let groups = root["groups"].as_array().expect("groups");
    let dims: Vec<i64> = groups.iter().map(|g| g["dim"].as_i64().unwrap()).collect();
    assert_eq!(dims, vec![8, 384, 768]);
    for group in groups {
        let dim = group["dim"].as_i64().unwrap();
        let query = floats(&group["query"]);
        let vectors = group["vectors"].as_array().expect("vectors");
        assert_eq!(vectors.len(), 20);
        for (n, entry) in vectors.iter().enumerate() {
            check(
                &format!("dim {dim} vector {n}"),
                &floats(&entry["v"]),
                &query,
                &ints(&entry["q"]),
                entry["scale"].as_f64().unwrap() as f32,
                entry["dot_query"].as_f64().unwrap() as f32,
            );
        }
    }
}

#[test]
fn edge_vectors_zero_one_hot_and_exact_half_ties() {
    let root = fixture();
    let edges = root["edge"].as_array().expect("edge");
    assert_eq!(edges.len(), 4);
    for edge in edges {
        check(
            edge["note"].as_str().unwrap(),
            &floats(&edge["v"]),
            &floats(&edge["query"]),
            &ints(&edge["q"]),
            edge["scale"].as_f64().unwrap() as f32,
            edge["dot_query"].as_f64().unwrap() as f32,
        );
    }
}
