import Foundation
import AriaLexiconLib

/// The projection of AriaLexicon onto MCP tools.
///
/// Per ARIA_MCP_SPEC_v0.2 §2: a tool exists because a caller-surfaced
/// verb exists, and its legal arguments are the nouns the verb accepts
/// under the acceptance matrix. The naming discipline is also fixed
/// at the spec layer: action tools take the form `verb_noun`
/// (`capture_drawer`) and the query tool takes the form `noun_verb`
/// (`drawer_recall`). The two substrate-driven verbs `propose` and
/// `associate` stay off the tool surface by design — they are emitted
/// by the Brain layer as notifications, not invoked by callers (§4).
///
/// The single source of truth for which (verb, noun) pairs are legal
/// is `AriaLexicon.Acceptance.verbs(for:)`. The projection enumerates
/// the full Cartesian product and keeps each pair the matrix accepts,
/// then names each pair by its verb's role. This guarantees the
/// lexicon-projected surface never drifts from the lexicon: when
/// AriaLexicon adds a noun, learn-from-it or capture-it tools appear
/// automatically.
///
/// ## Federation tools sit above the projection
///
/// Not every ARIA tool projects from the lexicon. `cross_estate_recall`
/// is a federation-surface tool with no `(verb, noun)` pair — it is
/// dispatched by name (see `ToolDispatcher`) and is the one tool
/// `tools()` appends explicitly *after* the lexicon projection loop. The
/// loop's output is still generated byte-for-byte from the acceptance
/// matrix; the federation tool is an additive, named entry
/// (`ToolProvenance.federation`) the conformance tests treat as the
/// single deliberate exception. This is the seam every future
/// non-lexicon ARIA tool follows (MCP-MULTI-01 Known Ambiguity §1, Kong
/// review).

/// Where a projected tool comes from. Named rather than a bare optional
/// `(verb, noun)` so a reader can tell a federation tool apart from a
/// lexicon tool with a forgotten pairing.
public enum ToolProvenance: Sendable, Equatable {
    /// Projected from an AriaLexicon acceptance-matrix `(verb, noun)`
    /// pair. The dispatcher routes these by re-parsing the tool name back
    /// to this pair.
    case lexicon(verb: Verb, noun: Noun)
    /// A federation-surface tool that sits above the lexicon projection.
    /// It has no `(verb, noun)` pair and is dispatched by name.
    case federation
    /// A CognitionKit behaviour-recipe tool that sits above the lexicon
    /// projection. Like `.federation` it has no `(verb, noun)` pair and is
    /// dispatched by name. The MCP↔CognitionKit channel is R/W: these are
    /// the conscious-mind recipes an agent triggers (and, for the
    /// migration flow, the human-confirmed promotion step).
    case recipe
    /// A VaultKit control-surface tool (`moot_vault_*`). Like `.federation`
    /// and `.recipe` it has no `(verb, noun)` pair and is dispatched by
    /// name. It bridges a MOOT estate and a Markdown vault (export /
    /// import / status / reconcile); Swift-only by design per
    /// ADR-VAULTKIT-002 (the shipped MCP binary is the Swift port).
    case vault
}

/// A single tool advertised in `tools/list`. The structure mirrors the
/// MCP `tools/list` schema closely enough to encode directly.
public struct ProjectedTool: Sendable, Equatable {
    /// The MCP tool name, already in projection form (`verb_noun` or
    /// `noun_verb`) for lexicon tools, or the fixed federation tool name.
    /// Stable across runs.
    public let name: String
    /// One-line description of what the tool does, surfaced in
    /// `tools/list` for client UIs.
    public let description: String
    /// JSON Schema for the tool's argument object. The dispatcher
    /// uses this to drive parameter decoding; clients use it to
    /// drive argument completion.
    public let inputSchema: JSONValue
    /// Where this tool comes from — a lexicon `(verb, noun)` pair or the
    /// federation surface above the projection.
    public let provenance: ToolProvenance

    /// The lexicon verb this tool projects from, or `nil` for a
    /// federation tool. Convenience over `provenance` for the conformance
    /// tests and any caller that only needs the pair.
    public var verb: Verb? {
        if case .lexicon(let verb, _) = provenance { return verb }
        return nil
    }
    /// The lexicon noun this tool projects from, or `nil` for a
    /// federation tool.
    public var noun: Noun? {
        if case .lexicon(_, let noun) = provenance { return noun }
        return nil
    }
}

public enum ToolProjection {

    /// Whether a verb participates in the MCP tool surface.
    ///
    /// `propose` and `associate` are substrate-driven per AriaLexicon's
    /// flow taxonomy (§4 of ARIA_MCP_SPEC_v0.2) and surface as
    /// notifications rather than callable tools. Every other verb —
    /// the six caller-driven ones and the grounding-driven `learn` —
    /// projects as a tool. This is the filter that the spec's
    /// "the seven caller-surfaced verbs" phrase corresponds to.
    public static func surfaces(_ verb: Verb) -> Bool {
        verb.flow != .substrateDriven
    }

    /// Project the lexicon's full acceptance matrix to the MCP tool
    /// list. Stable order: outer loop nouns in `Noun.allCases`, inner
    /// loop verbs in `Verb.allCases`. The conformance gate compares
    /// against this enumeration, so two implementations agree on the
    /// surface byte for byte.
    public static func tools() -> [ProjectedTool] {
        var out: [ProjectedTool] = []
        for noun in Noun.allCases {
            for verb in Verb.allCases where Acceptance.accepts(noun, verb) && surfaces(verb) {
                out.append(make(verb: verb, noun: noun))
            }
        }
        // The lexicon projection above is byte-for-byte from the matrix.
        // Append the one federation tool that sits above it — it has no
        // (verb, noun) pair and is dispatched by name. Server.swift builds
        // tools/list solely from this list, so the federation tool must
        // ride here to be advertised on the wire.
        out.append(federationTool())
        // CognitionKit behaviour-recipe tools sit above the lexicon
        // projection too (provenance `.recipe`, dispatched by name). They
        // are the conscious-mind surface the MCP↔CognitionKit R/W channel
        // exposes. Appended after the federation tool so the lexicon
        // projection's byte-for-byte conformance is untouched.
        out.append(contentsOf: RecipeTools.tools())
        // The reasoning-lens tools — one hard-bound tool per cataloged
        // lens recipe (LENS_DISCOVERABILITY_DECISION v2.0: listing and
        // invokability ship together).
        out.append(contentsOf: LensTools.tools())
        // The VaultKit control-surface tools — the `moot_vault_*` family
        // (export / import / status / reconcile). Dispatched by name like
        // the recipe and lens tools; appended after them so the lexicon
        // projection's byte-for-byte conformance is untouched.
        out.append(contentsOf: VaultTools.tools())
        return out
    }

    /// Build a single tool descriptor from a `(verb, noun)` pair.
    ///
    /// Tool naming: `recall` is the query verb (one of nine in the
    /// lexicon; the only one tagged as a read operation by the
    /// AriaLexicon flow / acceptance matrix), so it follows `noun_verb`.
    /// Every other surfaced verb is an action and follows `verb_noun`.
    /// See ARIA_MCP_SPEC_v0.2 §2 ("an action tool is verb-then-noun…
    /// and a query tool is noun-then-verb").
    public static func make(verb: Verb, noun: Noun) -> ProjectedTool {
        let name = toolName(verb: verb, noun: noun)
        return ProjectedTool(
            name: name,
            description: description(verb: verb, noun: noun),
            // Every per-estate tool gains an optional `estateID` so a
            // client can target a specific open estate; it is never
            // required, so the lightest call still targets the default.
            inputSchema: withEstateID(inputSchema(verb: verb, noun: noun)),
            provenance: .lexicon(verb: verb, noun: noun)
        )
    }

    /// The explicit, non-lexicon `cross_estate_recall` tool descriptor.
    ///
    /// This tool has no `(verb, noun)` pair: it is a federation-surface
    /// read that fans across the open estates the caller is entitled to
    /// read (the dispatcher routes it by name). Its schema names the
    /// required caller identity (`requesterEstateID` — the estate GLK's
    /// grant gate is evaluated against) plus the same optional recall
    /// shaping fields as `drawer_recall`. It carries no `estateID` field:
    /// the call fans across estates rather than targeting one.
    public static func federationTool() -> ProjectedTool {
        ProjectedTool(
            name: ToolDispatcher.crossEstateRecallToolName,
            description: "Grant-authorized cross-estate federated read: fans across the locally-open estates the requester is entitled to read and returns per-estate contributions, each narrowed to its grant's scope.",
            inputSchema: objectSchema(
                properties: [
                    "requesterEstateID": stringSchema("UUID of the requesting (caller) estate; the grant gate is evaluated against it. Must name an open estate."),
                    "filter": stringSchema("Filter kind: unconfirmed, userConfirmed, exportable, contained."),
                    "limit": integerSchema("Max rows per estate to return."),
                    "ordering": stringSchema("Ordering: byCaptureTimeDesc (default), byCaptureTimeAsc, byRoomAsc, byRelevanceDesc."),
                    "hydrationLevel": stringSchema("Hydration: structured (default), full, bitmapOnly."),
                ],
                required: ["requesterEstateID"]
            ),
            provenance: .federation
        )
    }

    /// Add an optional `estateID` property to an already-built object
    /// schema, without touching its `required` array — so addressing a
    /// non-default estate is always optional. Returns the schema
    /// unchanged if it is not an object schema with a properties map
    /// (the empty-fallback schema), which keeps this total and safe.
    private static func withEstateID(_ schema: JSONValue) -> JSONValue {
        guard case .object(var object) = schema,
              case .object(var properties)? = object["properties"] else {
            return schema
        }
        properties["estateID"] = stringSchema(
            "Optional UUID of the open estate to target. Omit for the default estate."
        )
        object["properties"] = .object(properties)
        return .object(object)
    }

    /// Product namespace prefix on every MCP tool name. The ARIA
    /// grammar (`verb_noun` / `noun_verb`) is the body; `moot_` marks
    /// the surface as MOOTx01's so it never collides with another
    /// connected MCP server's generic verbs. The dispatcher strips this
    /// prefix in `parseToolName` before re-parsing the grammar.
    public static let toolNamePrefix = "moot_"

    /// The MCP-facing tool name for a `(verb, noun)` pair.
    public static func toolName(verb: Verb, noun: Noun) -> String {
        switch verb {
        case .recall:
            return "\(toolNamePrefix)\(noun.rawValue)_\(verb.rawValue)"
        default:
            return "\(toolNamePrefix)\(verb.rawValue)_\(noun.rawValue)"
        }
    }

    /// One-line description for `tools/list`. Generated from the verb
    /// and noun so it stays consistent if the lexicon grows.
    private static func description(verb: Verb, noun: Noun) -> String {
        switch verb {
        case .capture: return "File a new \(noun.rawValue) into the estate."
        case .recall: return "Read \(noun.rawValue) rows back by filter."
        case .mutate: return "Apply a named mutation to a \(noun.rawValue)."
        case .withdraw: return "Withdraw a \(noun.rawValue) from active circulation."
        case .expunge: return "Hard-erase a \(noun.rawValue) (irreversible)."
        case .reanchor: return "Move where a \(noun.rawValue) sits in structure."
        case .learn: return "Ingest a canonical external \(noun.rawValue)."
        // propose and associate do not surface as tools per § 4.
        case .propose, .associate:
            return "Substrate-driven verb on \(noun.rawValue) (not callable as a tool)."
        }
    }

    /// Build the JSON Schema describing the tool's input arguments.
    ///
    /// The schemas are intentionally minimal — they match the slot
    /// sets of the GeniusLocusKit verb frames (CaptureFrame,
    /// RecallFrame, etc.). The tool dispatcher decodes against these
    /// schemas; clients use them for completion. As frames grow,
    /// schemas grow alongside them in `ToolDispatch.swift`.
    ///
    /// The schemas surface only the operand noun the matrix says the
    /// verb accepts; the noun is not a free-form argument. Adjective
    /// constraints (sensitivity, exportability) are expressed as
    /// optional fields, never required, so the lightest viable call
    /// stays small.
    private static func inputSchema(verb: Verb, noun: Noun) -> JSONValue {
        // Every projected tool's arguments live in a JSON object. The
        // required / optional fields and the per-field type sit here.
        switch (verb, noun) {
        case (.capture, .drawer):
            return objectSchema(
                properties: [
                    "content": stringSchema("Verbatim content to file."),
                    "room": stringSchema("Room within the estate."),
                    // The anchor code is interpreted under classificationScheme
                    // below. The arg name stays udcCode for wire compatibility;
                    // renaming the field is a separate storage migration (§5.8
                    // dual-scheme model, FUP follow-up), out of scope here.
                    "udcCode": stringSchema("Lattice anchor classification code (e.g. \"000.000\"), interpreted under classificationScheme."),
                    "classificationScheme": stringSchema("Optional classification scheme for the anchor code: \"udc\" (default) or \"mdcc\". Omitting it preserves UDC behavior."),
                    "addedBy": stringSchema("Actor identifier filed with the row."),
                    "embeddingModelID": stringSchema("Embedding model the row tags vectors with."),
                    "channel": stringSchema("Capture channel: typed, voiced, ocr, importedFile, sensor."),
                    "sensitivity": stringSchema("Sensitivity tier: normal, elevated, restricted, secret."),
                    "kind": stringSchema("Content kind: prose, code, transcript, list, structuredJSON, imageCaption."),
                ],
                required: ["content", "room", "udcCode", "addedBy", "embeddingModelID"]
            )
        case (.capture, .tunnel):
            // File a new directed-graph edge (tunnel) into the estate.
            // Schema is wire-identical to the Rust leg (rust/src/tool_list.rs
            // lexicon_schema Verb::Capture Noun::Tunnel): same property keys,
            // same required array. sourceDrawerID and targetDrawerID are optional
            // — they pin the edge to specific drawer rows. kind is the relation
            // label (free-form string); TunnelCaptureFrame uses it as label.
            // estateID is injected by withEstateID in make(verb:noun:) — not here.
            return objectSchema(
                properties: [
                    "sourceWing": stringSchema("Wing of the source drawer."),
                    "sourceRoom": stringSchema("Room of the source drawer."),
                    "targetWing": stringSchema("Wing of the target drawer."),
                    "targetRoom": stringSchema("Room of the target drawer."),
                    "kind": stringSchema("Tunnel kind: relates, precedes, contradicts, supports, refines, exemplifies, extends."),
                    "addedBy": stringSchema("Actor identifier filed with the tunnel."),
                    "sourceDrawerID": stringSchema("Optional source drawer id (drawer-to-drawer edge)."),
                    "targetDrawerID": stringSchema("Optional target drawer id."),
                ],
                required: ["sourceWing", "sourceRoom", "targetWing", "targetRoom", "kind", "addedBy"]
            )
        case (.recall, .drawer):
            return objectSchema(
                properties: [
                    "filter": stringSchema("Filter kind: unconfirmed, userConfirmed, exportable, contained."),
                    "limit": integerSchema("Max rows to return."),
                    "ordering": stringSchema("Ordering: byCaptureTimeDesc (default), byCaptureTimeAsc, byRoomAsc, byRelevanceDesc."),
                    "hydrationLevel": stringSchema("Hydration: structured (default), full, bitmapOnly."),
                ],
                required: []
            )
        case (.recall, .tunnel):
            // Read outgoing tunnel edges by source wing.
            // GeniusLocusKit.recallTunnels(_:wing:) is the dispatch target —
            // verified in GeniusLocusKit/Verbs/VerbSurface.swift:115.
            // Wire name is moot_tunnel_recall (noun_verb, same as drawer_recall).
            // Schema matches the Rust leg (rust/src/tool_list.rs tunnel_recall_tool):
            // wing is the single required argument. estateID is injected by the
            // withEstateID wrapper in make(verb:noun:) — not declared here.
            return objectSchema(
                properties: [
                    "wing": stringSchema("Wing to read outgoing tunnels from."),
                ],
                required: ["wing"]
            )
        case (.mutate, _):
            return objectSchema(
                properties: [
                    "rowID": stringSchema("Row identifier of the \(noun.rawValue)."),
                    "kind": stringSchema("Mutation kind: confirm, reject, contest, resolve, supersede, revive, accept."),
                    "payload": stringSchema("Optional free-text payload."),
                ],
                required: ["rowID", "kind"]
            )
        case (.withdraw, _):
            return objectSchema(
                properties: [
                    "rowID": stringSchema("Row identifier of the \(noun.rawValue)."),
                    "reason": stringSchema("Optional free-text justification."),
                ],
                required: ["rowID"]
            )
        case (.expunge, _):
            return objectSchema(
                properties: [
                    "rowID": stringSchema("Row identifier of the \(noun.rawValue)."),
                    "reason": stringSchema("Required free-text justification."),
                    "confirmation": booleanSchema("Must be true; expunge is irreversible."),
                ],
                required: ["rowID", "reason", "confirmation"]
            )
        case (.reanchor, _):
            return objectSchema(
                properties: [
                    "rowID": stringSchema("Row identifier of the \(noun.rawValue)."),
                    "toRoom": stringSchema("Optional target room."),
                    "toUDC": stringSchema("Optional target UDC code."),
                ],
                required: ["rowID"]
            )
        case (.learn, _):
            return objectSchema(
                properties: [
                    "handle": stringSchema("Source handle naming the reference to learn."),
                ],
                required: ["handle"]
            )
        case (.recall, _):
            // Generic recall schema for kgFact, diaryEntry, proposal, association,
            // and learnedReference. Mirrors the Rust leg's generic recall arm
            // (rust/src/tool_list.rs lexicon_schema Verb::Recall default arm):
            // same four optional frame-shape fields, empty required array.
            // The dispatcher surfaces an honest refusal (isError true)
            // for each of these nouns — the substrate lacks estate-wide accessors
            // for them. Schema is grounded so tools/list is informative rather
            // than advertising an empty fallback object, removing the empty-schema
            // divergence Adams documented for these six projected-but-dead tools.
            return objectSchema(
                properties: [
                    "filter": stringSchema("Filter kind: unconfirmed, userConfirmed, exportable, contained."),
                    "limit": integerSchema("Max rows to return."),
                    "ordering": stringSchema("Ordering: byCaptureTimeDesc (default), byCaptureTimeAsc, byRoomAsc, byRelevanceDesc."),
                    "hydrationLevel": stringSchema("Hydration: structured (default), full, bitmapOnly."),
                ],
                required: []
            )
        default:
            // propose and associate are filtered out above, so this
            // arm only fires if a future verb is added to the lexicon
            // without a schema mapping. Return an empty object so
            // `tools/list` still encodes; the dispatcher will refuse
            // the call with methodNotFound until a schema is added.
            return objectSchema(properties: [:], required: [])
        }
    }

    // MARK: - Schema helpers

    private static func objectSchema(
        properties: [String: JSONValue],
        required: [String]
    ) -> JSONValue {
        var schema: [String: JSONValue] = [
            "type": .string("object"),
            "properties": .object(properties),
        ]
        if !required.isEmpty {
            schema["required"] = .array(required.map { .string($0) })
        }
        return .object(schema)
    }

    private static func stringSchema(_ description: String) -> JSONValue {
        .object([
            "type": .string("string"),
            "description": .string(description),
        ])
    }

    private static func integerSchema(_ description: String) -> JSONValue {
        .object([
            "type": .string("integer"),
            "description": .string(description),
        ])
    }

    private static func booleanSchema(_ description: String) -> JSONValue {
        .object([
            "type": .string("boolean"),
            "description": .string(description),
        ])
    }
}
