import Testing
import Foundation
@testable import ContextDistillLib

@Suite("PassageViews")
struct PassageViewsTests {
    private struct Row: Decodable {
        let body: String; let query: String; let budget: Int; let expected: PassageViewPair
    }
    @Test func frozenPythonOracleAndExactPartition() throws {
        let rows = try JSONDecoder().decode([Row].self, from: Data(Self.oracle.utf8))
        #expect(rows.count == 71)
        for row in rows {
            let actual = try PassageViews.build(body: row.body, query: row.query, budget: row.budget)
            #expect(actual == row.expected, "body=\(row.body.debugDescription) query=\(row.query)")
            #expect(Array(actual.plain.fullText.utf8) == Array(row.body.utf8))
            if row.query.isEmpty { #expect(Array(actual.ordered.fullText.utf8) == Array(row.body.utf8)) }
            for result in [actual.plain, actual.ordered] {
                let source = Array(row.body.unicodeScalars)
                let ordered = result.spans.flatMap { Array(source[$0[0]..<$0[1]]) }
                #expect(Array(String(String.UnicodeScalarView(ordered)).utf8) == Array(result.fullText.utf8))
                var cursor = 0
                for span in result.spans.sorted(by: { $0[0] < $1[0] }) {
                    #expect(span[0] == cursor && span[1] > span[0]); cursor = span[1]
                }
                #expect(cursor == source.count)
                #expect(Array((result.text + result.continuation).utf8) == Array(result.fullText.utf8))
                #expect(result.returnedBytes == result.text.utf8.count)
            }
        }
    }
    @Test func explicitOversizedFirstGroupAndNoSkipping() throws {
        let result = try PassageViews.skim(body: "é🙂\n\nsmall", budget: 1, ordered: false)
        #expect(result.text == "é🙂\n\n")
        #expect(!result.budgetHonored && !result.complete)
        #expect(result.returnedBytes == 8 && result.continuation == "small")
        let blocked = try PassageViews.skim(body: "a\n\nlarge group\n\nx", budget: 5, ordered: false)
        #expect(blocked.text == "a\n\n" && blocked.continuation == "large group\n\nx")
        #expect(PassageViews.orderReducer(body: "a\n\nb", query: "b") == "b\n\na")
    }
    @Test func rejectsNonpositiveBudgets() {
        #expect(throws: PassageViewError.invalidBudget) { try PassageViews.build(body: "", query: "", budget: 0) }
        #expect(throws: PassageViewError.invalidBudget) { try PassageViews.build(body: "", query: "", budget: -1) }
    }
    // Frozen directly from the TokenSaver lab's reference views.py (Unicode 16).
    private static let oracle = #"""
[
{"body":"","query":"","budget":1,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"","continuation":"","full_text":"","complete":true,"budget_honored":true,"budget":1,"returned_bytes":0,"spans":[],"group_order":[]},"ordered":{"version":"dependency-groups-utf8-v1","text":"","continuation":"","full_text":"","complete":true,"budget_honored":true,"budget":1,"returned_bytes":0,"spans":[],"group_order":[]}}},
{"body":" \r\n\t","query":"x","budget":1,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":" \r\n\t","continuation":"","full_text":" \r\n\t","complete":true,"budget_honored":false,"budget":1,"returned_bytes":4,"spans":[[0,4]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":" \r\n\t","continuation":"","full_text":" \r\n\t","complete":true,"budget_honored":false,"budget":1,"returned_bytes":4,"spans":[[0,4]],"group_order":[0]}}},
{"body":" \r\n\t","query":"","budget":1,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":" \r\n\t","continuation":"","full_text":" \r\n\t","complete":true,"budget_honored":false,"budget":1,"returned_bytes":4,"spans":[[0,4]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":" \r\n\t","continuation":"","full_text":" \r\n\t","complete":true,"budget_honored":false,"budget":1,"returned_bytes":4,"spans":[[0,4]],"group_order":[0]}}},
{"body":"\nalpha\n\nbeta\n","query":"beta","budget":8,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"\nalpha\n\n","continuation":"beta\n","full_text":"\nalpha\n\nbeta\n","complete":false,"budget_honored":true,"budget":8,"returned_bytes":8,"spans":[[0,1],[1,6],[6,8],[8,12],[12,13]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"\nbeta\n\n","continuation":"alpha\n","full_text":"\nbeta\n\nalpha\n","complete":false,"budget_honored":true,"budget":8,"returned_bytes":7,"spans":[[0,1],[8,12],[6,8],[1,6],[12,13]],"group_order":[1,0]}}},
{"body":"\nalpha\n\nbeta\n","query":"","budget":8,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"\nalpha\n\n","continuation":"beta\n","full_text":"\nalpha\n\nbeta\n","complete":false,"budget_honored":true,"budget":8,"returned_bytes":8,"spans":[[0,1],[1,6],[6,8],[8,12],[12,13]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"\nalpha\n\n","continuation":"beta\n","full_text":"\nalpha\n\nbeta\n","complete":false,"budget_honored":true,"budget":8,"returned_bytes":8,"spans":[[0,1],[1,6],[6,8],[8,12],[12,13]],"group_order":[0,1]}}},
{"body":"\u00e9\ud83d\ude42 e\u0301\n\nStra\u00dfe\r\n\r\n\u03a3 \u03c2 \ufb03\n","query":"STRASSE","budget":7,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"\u00e9\ud83d\ude42 e\u0301\n\n","continuation":"Stra\u00dfe\r\n\r\n\u03a3 \u03c2 \ufb03\n","full_text":"\u00e9\ud83d\ude42 e\u0301\n\nStra\u00dfe\r\n\r\n\u03a3 \u03c2 \ufb03\n","complete":false,"budget_honored":false,"budget":7,"returned_bytes":12,"spans":[[0,5],[5,7],[7,13],[13,17],[17,22],[22,23]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"Stra\u00dfe\n\n","continuation":"\u00e9\ud83d\ude42 e\u0301\r\n\r\n\u03a3 \u03c2 \ufb03\n","full_text":"Stra\u00dfe\n\n\u00e9\ud83d\ude42 e\u0301\r\n\r\n\u03a3 \u03c2 \ufb03\n","complete":false,"budget_honored":false,"budget":7,"returned_bytes":9,"spans":[[7,13],[5,7],[0,5],[13,17],[17,22],[22,23]],"group_order":[1,0,2]}}},
{"body":"\u00e9\ud83d\ude42 e\u0301\n\nStra\u00dfe\r\n\r\n\u03a3 \u03c2 \ufb03\n","query":"","budget":7,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"\u00e9\ud83d\ude42 e\u0301\n\n","continuation":"Stra\u00dfe\r\n\r\n\u03a3 \u03c2 \ufb03\n","full_text":"\u00e9\ud83d\ude42 e\u0301\n\nStra\u00dfe\r\n\r\n\u03a3 \u03c2 \ufb03\n","complete":false,"budget_honored":false,"budget":7,"returned_bytes":12,"spans":[[0,5],[5,7],[7,13],[13,17],[17,22],[22,23]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"\u00e9\ud83d\ude42 e\u0301\n\n","continuation":"Stra\u00dfe\r\n\r\n\u03a3 \u03c2 \ufb03\n","full_text":"\u00e9\ud83d\ude42 e\u0301\n\nStra\u00dfe\r\n\r\n\u03a3 \u03c2 \ufb03\n","complete":false,"budget_honored":false,"budget":7,"returned_bytes":12,"spans":[[0,5],[5,7],[7,13],[13,17],[17,22],[22,23]],"group_order":[0,1,2]}}},
{"body":"apple\n\npear\n\napple","query":"apple","budget":8,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"apple\n\n","continuation":"pear\n\napple","full_text":"apple\n\npear\n\napple","complete":false,"budget_honored":true,"budget":8,"returned_bytes":7,"spans":[[0,5],[5,7],[7,11],[11,13],[13,18]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"apple\n\n","continuation":"apple\n\npear","full_text":"apple\n\napple\n\npear","complete":false,"budget_honored":true,"budget":8,"returned_bytes":7,"spans":[[0,5],[5,7],[13,18],[11,13],[7,11]],"group_order":[0,2,1]}}},
{"body":"apple\n\npear\n\napple","query":"","budget":8,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"apple\n\n","continuation":"pear\n\napple","full_text":"apple\n\npear\n\napple","complete":false,"budget_honored":true,"budget":8,"returned_bytes":7,"spans":[[0,5],[5,7],[7,11],[11,13],[13,18]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"apple\n\n","continuation":"pear\n\napple","full_text":"apple\n\npear\n\napple","complete":false,"budget_honored":true,"budget":8,"returned_bytes":7,"spans":[[0,5],[5,7],[7,11],[11,13],[13,18]],"group_order":[0,1,2]}}},
{"body":"long first group\n\nx","query":"x","budget":1,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"long first group\n\n","continuation":"x","full_text":"long first group\n\nx","complete":false,"budget_honored":false,"budget":1,"returned_bytes":18,"spans":[[0,16],[16,18],[18,19]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"x\n\n","continuation":"long first group","full_text":"x\n\nlong first group","complete":false,"budget_honored":false,"budget":1,"returned_bytes":3,"spans":[[18,19],[16,18],[0,16]],"group_order":[1,0]}}},
{"body":"long first group\n\nx","query":"","budget":1,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"long first group\n\n","continuation":"x","full_text":"long first group\n\nx","complete":false,"budget_honored":false,"budget":1,"returned_bytes":18,"spans":[[0,16],[16,18],[18,19]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"long first group\n\n","continuation":"x","full_text":"long first group\n\nx","complete":false,"budget_honored":false,"budget":1,"returned_bytes":18,"spans":[[0,16],[16,18],[18,19]],"group_order":[0,1]}}},
{"body":"# A\n\ntext\n\n## B\n\nchild\n\n# C\n\nend","query":"end","budget":10,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"# A\n\ntext\n\n## B\n\nchild\n\n","continuation":"# C\n\nend","full_text":"# A\n\ntext\n\n## B\n\nchild\n\n# C\n\nend","complete":false,"budget_honored":false,"budget":10,"returned_bytes":24,"spans":[[0,22],[22,24],[24,32]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"# C\n\nend\n\n","continuation":"# A\n\ntext\n\n## B\n\nchild","full_text":"# C\n\nend\n\n# A\n\ntext\n\n## B\n\nchild","complete":false,"budget_honored":true,"budget":10,"returned_bytes":10,"spans":[[24,32],[22,24],[0,22]],"group_order":[1,0]}}},
{"body":"# A\n\ntext\n\n## B\n\nchild\n\n# C\n\nend","query":"","budget":10,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"# A\n\ntext\n\n## B\n\nchild\n\n","continuation":"# C\n\nend","full_text":"# A\n\ntext\n\n## B\n\nchild\n\n# C\n\nend","complete":false,"budget_honored":false,"budget":10,"returned_bytes":24,"spans":[[0,22],[22,24],[24,32]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"# A\n\ntext\n\n## B\n\nchild\n\n","continuation":"# C\n\nend","full_text":"# A\n\ntext\n\n## B\n\nchild\n\n# C\n\nend","complete":false,"budget_honored":false,"budget":10,"returned_bytes":24,"spans":[[0,22],[22,24],[24,32]],"group_order":[0,1]}}},
{"body":"Label:\n\nvalue\n\nfree","query":"free","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"Label:\n\nvalue\n\n","continuation":"free","full_text":"Label:\n\nvalue\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":15,"spans":[[0,13],[13,15],[15,19]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"free\n\n","continuation":"Label:\n\nvalue","full_text":"free\n\nLabel:\n\nvalue","complete":false,"budget_honored":false,"budget":3,"returned_bytes":6,"spans":[[15,19],[13,15],[0,13]],"group_order":[1,0]}}},
{"body":"Label:\n\nvalue\n\nfree","query":"","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"Label:\n\nvalue\n\n","continuation":"free","full_text":"Label:\n\nvalue\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":15,"spans":[[0,13],[13,15],[15,19]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"Label:\n\nvalue\n\n","continuation":"free","full_text":"Label:\n\nvalue\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":15,"spans":[[0,13],[13,15],[15,19]],"group_order":[0,1]}}},
{"body":"**Label**\n\nvalue\n\nfree","query":"free","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"**Label**\n\nvalue\n\n","continuation":"free","full_text":"**Label**\n\nvalue\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":18,"spans":[[0,16],[16,18],[18,22]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"free\n\n","continuation":"**Label**\n\nvalue","full_text":"free\n\n**Label**\n\nvalue","complete":false,"budget_honored":false,"budget":3,"returned_bytes":6,"spans":[[18,22],[16,18],[0,16]],"group_order":[1,0]}}},
{"body":"**Label**\n\nvalue\n\nfree","query":"","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"**Label**\n\nvalue\n\n","continuation":"free","full_text":"**Label**\n\nvalue\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":18,"spans":[[0,16],[16,18],[18,22]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"**Label**\n\nvalue\n\n","continuation":"free","full_text":"**Label**\n\nvalue\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":18,"spans":[[0,16],[16,18],[18,22]],"group_order":[0,1]}}},
{"body":"- first\n\n- second\n\nfree","query":"free","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"- first\n\n- second\n\n","continuation":"free","full_text":"- first\n\n- second\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":19,"spans":[[0,17],[17,19],[19,23]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"free\n\n","continuation":"- first\n\n- second","full_text":"free\n\n- first\n\n- second","complete":false,"budget_honored":false,"budget":3,"returned_bytes":6,"spans":[[19,23],[17,19],[0,17]],"group_order":[1,0]}}},
{"body":"- first\n\n- second\n\nfree","query":"","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"- first\n\n- second\n\n","continuation":"free","full_text":"- first\n\n- second\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":19,"spans":[[0,17],[17,19],[19,23]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"- first\n\n- second\n\n","continuation":"free","full_text":"- first\n\n- second\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":19,"spans":[[0,17],[17,19],[19,23]],"group_order":[0,1]}}},
{"body":"one\n\n    code\n\nfree","query":"free","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n    code\n\n","continuation":"free","full_text":"one\n\n    code\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":15,"spans":[[0,13],[13,15],[15,19]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"free\n\n","continuation":"one\n\n    code","full_text":"free\n\none\n\n    code","complete":false,"budget_honored":false,"budget":3,"returned_bytes":6,"spans":[[15,19],[13,15],[0,13]],"group_order":[1,0]}}},
{"body":"one\n\n    code\n\nfree","query":"","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n    code\n\n","continuation":"free","full_text":"one\n\n    code\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":15,"spans":[[0,13],[13,15],[15,19]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\n    code\n\n","continuation":"free","full_text":"one\n\n    code\n\nfree","complete":false,"budget_honored":false,"budget":3,"returned_bytes":15,"spans":[[0,13],[13,15],[15,19]],"group_order":[0,1]}}},
{"body":"one\n\n```py\na\n\nb\n```\n\nfree","query":"free","budget":5,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"```py\na\n\nb\n```\n\nfree","full_text":"one\n\n```py\na\n\nb\n```\n\nfree","complete":false,"budget_honored":true,"budget":5,"returned_bytes":5,"spans":[[0,3],[3,5],[5,19],[19,21],[21,25]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"free\n\n","continuation":"one\n\n```py\na\n\nb\n```","full_text":"free\n\none\n\n```py\na\n\nb\n```","complete":false,"budget_honored":false,"budget":5,"returned_bytes":6,"spans":[[21,25],[3,5],[0,3],[19,21],[5,19]],"group_order":[2,0,1]}}},
{"body":"one\n\n```py\na\n\nb\n```\n\nfree","query":"","budget":5,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"```py\na\n\nb\n```\n\nfree","full_text":"one\n\n```py\na\n\nb\n```\n\nfree","complete":false,"budget_honored":true,"budget":5,"returned_bytes":5,"spans":[[0,3],[3,5],[5,19],[19,21],[21,25]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"```py\na\n\nb\n```\n\nfree","full_text":"one\n\n```py\na\n\nb\n```\n\nfree","complete":false,"budget_honored":true,"budget":5,"returned_bytes":5,"spans":[[0,3],[3,5],[5,19],[19,21],[21,25]],"group_order":[0,1,2]}}},
{"body":"one\n\n~~~\nx\n~~~~\n\nfree","query":"free","budget":5,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"~~~\nx\n~~~~\n\nfree","full_text":"one\n\n~~~\nx\n~~~~\n\nfree","complete":false,"budget_honored":true,"budget":5,"returned_bytes":5,"spans":[[0,3],[3,5],[5,15],[15,17],[17,21]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"free\n\n","continuation":"one\n\n~~~\nx\n~~~~","full_text":"free\n\none\n\n~~~\nx\n~~~~","complete":false,"budget_honored":false,"budget":5,"returned_bytes":6,"spans":[[17,21],[3,5],[0,3],[15,17],[5,15]],"group_order":[2,0,1]}}},
{"body":"one\n\n~~~\nx\n~~~~\n\nfree","query":"","budget":5,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"~~~\nx\n~~~~\n\nfree","full_text":"one\n\n~~~\nx\n~~~~\n\nfree","complete":false,"budget_honored":true,"budget":5,"returned_bytes":5,"spans":[[0,3],[3,5],[5,15],[15,17],[17,21]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"~~~\nx\n~~~~\n\nfree","full_text":"one\n\n~~~\nx\n~~~~\n\nfree","complete":false,"budget_honored":true,"budget":5,"returned_bytes":5,"spans":[[0,3],[3,5],[5,15],[15,17],[17,21]],"group_order":[0,1,2]}}},
{"body":"one\n\n```a`b\nx\n```\n\nfree","query":"free","budget":5,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n```a`b\nx\n```\n\nfree","continuation":"","full_text":"one\n\n```a`b\nx\n```\n\nfree","complete":true,"budget_honored":false,"budget":5,"returned_bytes":23,"spans":[[0,23]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\n```a`b\nx\n```\n\nfree","continuation":"","full_text":"one\n\n```a`b\nx\n```\n\nfree","complete":true,"budget_honored":false,"budget":5,"returned_bytes":23,"spans":[[0,23]],"group_order":[0]}}},
{"body":"one\n\n```a`b\nx\n```\n\nfree","query":"","budget":5,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n```a`b\nx\n```\n\nfree","continuation":"","full_text":"one\n\n```a`b\nx\n```\n\nfree","complete":true,"budget_honored":false,"budget":5,"returned_bytes":23,"spans":[[0,23]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\n```a`b\nx\n```\n\nfree","continuation":"","full_text":"one\n\n```a`b\nx\n```\n\nfree","complete":true,"budget_honored":false,"budget":5,"returned_bytes":23,"spans":[[0,23]],"group_order":[0]}}},
{"body":"one\n\n```\nx","query":"x","budget":1,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n```\nx","continuation":"","full_text":"one\n\n```\nx","complete":true,"budget_honored":false,"budget":1,"returned_bytes":10,"spans":[[0,10]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\n```\nx","continuation":"","full_text":"one\n\n```\nx","complete":true,"budget_honored":false,"budget":1,"returned_bytes":10,"spans":[[0,10]],"group_order":[0]}}},
{"body":"one\n\n```\nx","query":"","budget":1,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n```\nx","continuation":"","full_text":"one\n\n```\nx","complete":true,"budget_honored":false,"budget":1,"returned_bytes":10,"spans":[[0,10]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\n```\nx","continuation":"","full_text":"one\n\n```\nx","complete":true,"budget_honored":false,"budget":1,"returned_bytes":10,"spans":[[0,10]],"group_order":[0]}}},
{"body":"one\n\nabove thing","query":"above","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\nabove thing","continuation":"","full_text":"one\n\nabove thing","complete":true,"budget_honored":false,"budget":2,"returned_bytes":16,"spans":[[0,16]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\nabove thing","continuation":"","full_text":"one\n\nabove thing","complete":true,"budget_honored":false,"budget":2,"returned_bytes":16,"spans":[[0,16]],"group_order":[0]}}},
{"body":"one\n\nabove thing","query":"","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\nabove thing","continuation":"","full_text":"one\n\nabove thing","complete":true,"budget_honored":false,"budget":2,"returned_bytes":16,"spans":[[0,16]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\nabove thing","continuation":"","full_text":"one\n\nabove thing","complete":true,"budget_honored":false,"budget":2,"returned_bytes":16,"spans":[[0,16]],"group_order":[0]}}},
{"body":"User: x\n\nnext","query":"next","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"User: x\n\nnext","continuation":"","full_text":"User: x\n\nnext","complete":true,"budget_honored":false,"budget":2,"returned_bytes":13,"spans":[[0,13]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"User: x\n\nnext","continuation":"","full_text":"User: x\n\nnext","complete":true,"budget_honored":false,"budget":2,"returned_bytes":13,"spans":[[0,13]],"group_order":[0]}}},
{"body":"User: x\n\nnext","query":"","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"User: x\n\nnext","continuation":"","full_text":"User: x\n\nnext","complete":true,"budget_honored":false,"budget":2,"returned_bytes":13,"spans":[[0,13]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"User: x\n\nnext","continuation":"","full_text":"User: x\n\nnext","complete":true,"budget_honored":false,"budget":2,"returned_bytes":13,"spans":[[0,13]],"group_order":[0]}}},
{"body":"one\n\nHowever, x","query":"x","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\nHowever, x","continuation":"","full_text":"one\n\nHowever, x","complete":true,"budget_honored":false,"budget":2,"returned_bytes":15,"spans":[[0,15]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\nHowever, x","continuation":"","full_text":"one\n\nHowever, x","complete":true,"budget_honored":false,"budget":2,"returned_bytes":15,"spans":[[0,15]],"group_order":[0]}}},
{"body":"one\n\nHowever, x","query":"","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\nHowever, x","continuation":"","full_text":"one\n\nHowever, x","complete":true,"budget_honored":false,"budget":2,"returned_bytes":15,"spans":[[0,15]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\nHowever, x","continuation":"","full_text":"one\n\nHowever, x","complete":true,"budget_honored":false,"budget":2,"returned_bytes":15,"spans":[[0,15]],"group_order":[0]}}},
{"body":"one\n\nTitle\n---\n\nfree","query":"free","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\nTitle\n---\n\nfree","continuation":"","full_text":"one\n\nTitle\n---\n\nfree","complete":true,"budget_honored":false,"budget":2,"returned_bytes":20,"spans":[[0,20]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\nTitle\n---\n\nfree","continuation":"","full_text":"one\n\nTitle\n---\n\nfree","complete":true,"budget_honored":false,"budget":2,"returned_bytes":20,"spans":[[0,20]],"group_order":[0]}}},
{"body":"one\n\nTitle\n---\n\nfree","query":"","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\nTitle\n---\n\nfree","continuation":"","full_text":"one\n\nTitle\n---\n\nfree","complete":true,"budget_honored":false,"budget":2,"returned_bytes":20,"spans":[[0,20]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\nTitle\n---\n\nfree","continuation":"","full_text":"one\n\nTitle\n---\n\nfree","complete":true,"budget_honored":false,"budget":2,"returned_bytes":20,"spans":[[0,20]],"group_order":[0]}}},
{"body":"one\r\n\r\ntwo\r\n","query":"two","budget":5,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\r\n\r\n","continuation":"two\r\n","full_text":"one\r\n\r\ntwo\r\n","complete":false,"budget_honored":false,"budget":5,"returned_bytes":7,"spans":[[0,3],[3,7],[7,10],[10,12]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"two\r\n\r\n","continuation":"one\r\n","full_text":"two\r\n\r\none\r\n","complete":false,"budget_honored":false,"budget":5,"returned_bytes":7,"spans":[[7,10],[3,7],[0,3],[10,12]],"group_order":[1,0]}}},
{"body":"one\r\n\r\ntwo\r\n","query":"","budget":5,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\r\n\r\n","continuation":"two\r\n","full_text":"one\r\n\r\ntwo\r\n","complete":false,"budget_honored":false,"budget":5,"returned_bytes":7,"spans":[[0,3],[3,7],[7,10],[10,12]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\r\n\r\n","continuation":"two\r\n","full_text":"one\r\n\r\ntwo\r\n","complete":false,"budget_honored":false,"budget":5,"returned_bytes":7,"spans":[[0,3],[3,7],[7,10],[10,12]],"group_order":[0,1]}}},
{"body":"a\u2028\u2028b","query":"b","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\u2028\u2028","continuation":"b","full_text":"a\u2028\u2028b","complete":false,"budget_honored":false,"budget":2,"returned_bytes":7,"spans":[[0,2],[2,3],[3,4]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"b\u2028","continuation":"a\u2028","full_text":"b\u2028a\u2028","complete":false,"budget_honored":false,"budget":2,"returned_bytes":4,"spans":[[3,4],[2,3],[0,2]],"group_order":[1,0]}}},
{"body":"a\u2028\u2028b","query":"","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\u2028\u2028","continuation":"b","full_text":"a\u2028\u2028b","complete":false,"budget_honored":false,"budget":2,"returned_bytes":7,"spans":[[0,2],[2,3],[3,4]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"a\u2028\u2028","continuation":"b","full_text":"a\u2028\u2028b","complete":false,"budget_honored":false,"budget":2,"returned_bytes":7,"spans":[[0,2],[2,3],[3,4]],"group_order":[0,1]}}},
{"body":"a\u001c\u001cb","query":"b","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\u001c\u001c","continuation":"b","full_text":"a\u001c\u001cb","complete":false,"budget_honored":false,"budget":2,"returned_bytes":3,"spans":[[0,2],[2,3],[3,4]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"b\u001c","continuation":"a\u001c","full_text":"b\u001ca\u001c","complete":false,"budget_honored":true,"budget":2,"returned_bytes":2,"spans":[[3,4],[2,3],[0,2]],"group_order":[1,0]}}},
{"body":"a\u001c\u001cb","query":"","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\u001c\u001c","continuation":"b","full_text":"a\u001c\u001cb","complete":false,"budget_honored":false,"budget":2,"returned_bytes":3,"spans":[[0,2],[2,3],[3,4]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"a\u001c\u001c","continuation":"b","full_text":"a\u001c\u001cb","complete":false,"budget_honored":false,"budget":2,"returned_bytes":3,"spans":[[0,2],[2,3],[3,4]],"group_order":[0,1]}}},
{"body":"alpha\n\n\u0661. first\n\n\u0662. second\n\nfree","query":"free","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"alpha\n\n","continuation":"\u0661. first\n\n\u0662. second\n\nfree","full_text":"alpha\n\n\u0661. first\n\n\u0662. second\n\nfree","complete":false,"budget_honored":false,"budget":4,"returned_bytes":7,"spans":[[0,5],[5,7],[7,26],[26,28],[28,32]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"free\n\n","continuation":"alpha\n\n\u0661. first\n\n\u0662. second","full_text":"free\n\nalpha\n\n\u0661. first\n\n\u0662. second","complete":false,"budget_honored":false,"budget":4,"returned_bytes":6,"spans":[[28,32],[5,7],[0,5],[26,28],[7,26]],"group_order":[2,0,1]}}},
{"body":"alpha\n\n\u0661. first\n\n\u0662. second\n\nfree","query":"","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"alpha\n\n","continuation":"\u0661. first\n\n\u0662. second\n\nfree","full_text":"alpha\n\n\u0661. first\n\n\u0662. second\n\nfree","complete":false,"budget_honored":false,"budget":4,"returned_bytes":7,"spans":[[0,5],[5,7],[7,26],[26,28],[28,32]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"alpha\n\n","continuation":"\u0661. first\n\n\u0662. second\n\nfree","full_text":"alpha\n\n\u0661. first\n\n\u0662. second\n\nfree","complete":false,"budget_honored":false,"budget":4,"returned_bytes":7,"spans":[[0,5],[5,7],[7,26],[26,28],[28,32]],"group_order":[0,1,2]}}},
{"body":"one\n\nSOURCE: x","query":"x","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\nSOURCE: x","continuation":"","full_text":"one\n\nSOURCE: x","complete":true,"budget_honored":false,"budget":4,"returned_bytes":14,"spans":[[0,14]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\nSOURCE: x","continuation":"","full_text":"one\n\nSOURCE: x","complete":true,"budget_honored":false,"budget":4,"returned_bytes":14,"spans":[[0,14]],"group_order":[0]}}},
{"body":"one\n\nSOURCE: x","query":"","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\nSOURCE: x","continuation":"","full_text":"one\n\nSOURCE: x","complete":true,"budget_honored":false,"budget":4,"returned_bytes":14,"spans":[[0,14]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\nSOURCE: x","continuation":"","full_text":"one\n\nSOURCE: x","complete":true,"budget_honored":false,"budget":4,"returned_bytes":14,"spans":[[0,14]],"group_order":[0]}}},
{"body":"a\n\n\u0130t changes","query":"changes","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\n\n\u0130t changes","continuation":"","full_text":"a\n\n\u0130t changes","complete":true,"budget_honored":false,"budget":4,"returned_bytes":14,"spans":[[0,13]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"a\n\n\u0130t changes","continuation":"","full_text":"a\n\n\u0130t changes","complete":true,"budget_honored":false,"budget":4,"returned_bytes":14,"spans":[[0,13]],"group_order":[0]}}},
{"body":"a\n\n\u0130t changes","query":"","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\n\n\u0130t changes","continuation":"","full_text":"a\n\n\u0130t changes","complete":true,"budget_honored":false,"budget":4,"returned_bytes":14,"spans":[[0,13]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"a\n\n\u0130t changes","continuation":"","full_text":"a\n\n\u0130t changes","complete":true,"budget_honored":false,"budget":4,"returned_bytes":14,"spans":[[0,13]],"group_order":[0]}}},
{"body":"a\n\n\u0131tem is distinct","query":"item","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\n\n","continuation":"\u0131tem is distinct","full_text":"a\n\n\u0131tem is distinct","complete":false,"budget_honored":true,"budget":4,"returned_bytes":3,"spans":[[0,1],[1,3],[3,19]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"a\n\n","continuation":"\u0131tem is distinct","full_text":"a\n\n\u0131tem is distinct","complete":false,"budget_honored":true,"budget":4,"returned_bytes":3,"spans":[[0,1],[1,3],[3,19]],"group_order":[0,1]}}},
{"body":"a\n\n\u0131tem is distinct","query":"","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\n\n","continuation":"\u0131tem is distinct","full_text":"a\n\n\u0131tem is distinct","complete":false,"budget_honored":true,"budget":4,"returned_bytes":3,"spans":[[0,1],[1,3],[3,19]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"a\n\n","continuation":"\u0131tem is distinct","full_text":"a\n\n\u0131tem is distinct","complete":false,"budget_honored":true,"budget":4,"returned_bytes":3,"spans":[[0,1],[1,3],[3,19]],"group_order":[0,1]}}},
{"body":"a\n\nOnly\tif enabled","query":"enabled","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\n\nOnly\tif enabled","continuation":"","full_text":"a\n\nOnly\tif enabled","complete":true,"budget_honored":false,"budget":4,"returned_bytes":18,"spans":[[0,18]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"a\n\nOnly\tif enabled","continuation":"","full_text":"a\n\nOnly\tif enabled","complete":true,"budget_honored":false,"budget":4,"returned_bytes":18,"spans":[[0,18]],"group_order":[0]}}},
{"body":"a\n\nOnly\tif enabled","query":"","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\n\nOnly\tif enabled","continuation":"","full_text":"a\n\nOnly\tif enabled","complete":true,"budget_honored":false,"budget":4,"returned_bytes":18,"spans":[[0,18]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"a\n\nOnly\tif enabled","continuation":"","full_text":"a\n\nOnly\tif enabled","complete":true,"budget_honored":false,"budget":4,"returned_bytes":18,"spans":[[0,18]],"group_order":[0]}}},
{"body":"o\n\nquoted from x","query":"x","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"o\n\nquoted from x","continuation":"","full_text":"o\n\nquoted from x","complete":true,"budget_honored":false,"budget":4,"returned_bytes":16,"spans":[[0,16]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"o\n\nquoted from x","continuation":"","full_text":"o\n\nquoted from x","complete":true,"budget_honored":false,"budget":4,"returned_bytes":16,"spans":[[0,16]],"group_order":[0]}}},
{"body":"o\n\nquoted from x","query":"","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"o\n\nquoted from x","continuation":"","full_text":"o\n\nquoted from x","complete":true,"budget_honored":false,"budget":4,"returned_bytes":16,"spans":[[0,16]],"group_order":[0]},"ordered":{"version":"dependency-groups-utf8-v1","text":"o\n\nquoted from x","continuation":"","full_text":"o\n\nquoted from x","complete":true,"budget_honored":false,"budget":4,"returned_bytes":16,"spans":[[0,16]],"group_order":[0]}}},
{"body":"one\n\n###\u2028\n\nfree","query":"free","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"###\u2028\n\nfree","full_text":"one\n\n###\u2028\n\nfree","complete":false,"budget_honored":false,"budget":4,"returned_bytes":5,"spans":[[0,3],[3,5],[5,9],[9,11],[11,15]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"free\n\n","continuation":"one\n\n###\u2028","full_text":"free\n\none\n\n###\u2028","complete":false,"budget_honored":false,"budget":4,"returned_bytes":6,"spans":[[11,15],[3,5],[0,3],[9,11],[5,9]],"group_order":[2,0,1]}}},
{"body":"one\n\n###\u2028\n\nfree","query":"","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"###\u2028\n\nfree","full_text":"one\n\n###\u2028\n\nfree","complete":false,"budget_honored":false,"budget":4,"returned_bytes":5,"spans":[[0,3],[3,5],[5,9],[9,11],[11,15]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"###\u2028\n\nfree","full_text":"one\n\n###\u2028\n\nfree","complete":false,"budget_honored":false,"budget":4,"returned_bytes":5,"spans":[[0,3],[3,5],[5,9],[9,11],[11,15]],"group_order":[0,1,2]}}},
{"body":"one\n\nsource_code","query":"source_code","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"source_code","full_text":"one\n\nsource_code","complete":false,"budget_honored":false,"budget":4,"returned_bytes":5,"spans":[[0,3],[3,5],[5,16]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"source_code\n\n","continuation":"one","full_text":"source_code\n\none","complete":false,"budget_honored":false,"budget":4,"returned_bytes":13,"spans":[[5,16],[3,5],[0,3]],"group_order":[1,0]}}},
{"body":"one\n\nsource_code","query":"","budget":4,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"source_code","full_text":"one\n\nsource_code","complete":false,"budget_honored":false,"budget":4,"returned_bytes":5,"spans":[[0,3],[3,5],[5,16]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"one\n\n","continuation":"source_code","full_text":"one\n\nsource_code","complete":false,"budget_honored":false,"budget":4,"returned_bytes":5,"spans":[[0,3],[3,5],[5,16]],"group_order":[0,1]}}},
{"body":"  \n\nA\n \nB\n\n\t","query":"B","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"  \n\nA\n \n","continuation":"B\n\n\t","full_text":"  \n\nA\n \nB\n\n\t","complete":false,"budget_honored":false,"budget":3,"returned_bytes":8,"spans":[[0,4],[4,5],[5,8],[8,9],[9,12]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"  \n\nB\n \n","continuation":"A\n\n\t","full_text":"  \n\nB\n \nA\n\n\t","complete":false,"budget_honored":false,"budget":3,"returned_bytes":8,"spans":[[0,4],[8,9],[5,8],[4,5],[9,12]],"group_order":[1,0]}}},
{"body":"  \n\nA\n \nB\n\n\t","query":"","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"  \n\nA\n \n","continuation":"B\n\n\t","full_text":"  \n\nA\n \nB\n\n\t","complete":false,"budget_honored":false,"budget":3,"returned_bytes":8,"spans":[[0,4],[4,5],[5,8],[8,9],[9,12]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"  \n\nA\n \n","continuation":"B\n\n\t","full_text":"  \n\nA\n \nB\n\n\t","complete":false,"budget_honored":false,"budget":3,"returned_bytes":8,"spans":[[0,4],[4,5],[5,8],[8,9],[9,12]],"group_order":[0,1]}}},
{"body":"unmatched\n\n\u00df\n\n\u1e9e","query":"SS","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"unmatched\n\n","continuation":"\u00df\n\n\u1e9e","full_text":"unmatched\n\n\u00df\n\n\u1e9e","complete":false,"budget_honored":false,"budget":2,"returned_bytes":11,"spans":[[0,9],[9,11],[11,12],[12,14],[14,15]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"\u00df\n\n","continuation":"\u1e9e\n\nunmatched","full_text":"\u00df\n\n\u1e9e\n\nunmatched","complete":false,"budget_honored":false,"budget":2,"returned_bytes":4,"spans":[[11,12],[9,11],[14,15],[12,14],[0,9]],"group_order":[1,2,0]}}},
{"body":"unmatched\n\n\u00df\n\n\u1e9e","query":"","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"unmatched\n\n","continuation":"\u00df\n\n\u1e9e","full_text":"unmatched\n\n\u00df\n\n\u1e9e","complete":false,"budget_honored":false,"budget":2,"returned_bytes":11,"spans":[[0,9],[9,11],[11,12],[12,14],[14,15]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"unmatched\n\n","continuation":"\u00df\n\n\u1e9e","full_text":"unmatched\n\n\u00df\n\n\u1e9e","complete":false,"budget_honored":false,"budget":2,"returned_bytes":11,"spans":[[0,9],[9,11],[11,12],[12,14],[14,15]],"group_order":[0,1,2]}}},
{"body":"\u13a0\n\n\uab70\n\nother","query":"\uab70","budget":5,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"\u13a0\n\n","continuation":"\uab70\n\nother","full_text":"\u13a0\n\n\uab70\n\nother","complete":false,"budget_honored":true,"budget":5,"returned_bytes":5,"spans":[[0,1],[1,3],[3,4],[4,6],[6,11]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"\u13a0\n\n","continuation":"\uab70\n\nother","full_text":"\u13a0\n\n\uab70\n\nother","complete":false,"budget_honored":true,"budget":5,"returned_bytes":5,"spans":[[0,1],[1,3],[3,4],[4,6],[6,11]],"group_order":[0,1,2]}}},
{"body":"\u13a0\n\n\uab70\n\nother","query":"","budget":5,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"\u13a0\n\n","continuation":"\uab70\n\nother","full_text":"\u13a0\n\n\uab70\n\nother","complete":false,"budget_honored":true,"budget":5,"returned_bytes":5,"spans":[[0,1],[1,3],[3,4],[4,6],[6,11]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"\u13a0\n\n","continuation":"\uab70\n\nother","full_text":"\u13a0\n\n\uab70\n\nother","complete":false,"budget_honored":true,"budget":5,"returned_bytes":5,"spans":[[0,1],[1,3],[3,4],[4,6],[6,11]],"group_order":[0,1,2]}}},
{"body":"a\n\n\u0345\n\nb","query":"\u0345","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\n\n","continuation":"\u0345\n\nb","full_text":"a\n\n\u0345\n\nb","complete":false,"budget_honored":false,"budget":2,"returned_bytes":3,"spans":[[0,1],[1,3],[3,4],[4,6],[6,7]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"\u0345\n\n","continuation":"a\n\nb","full_text":"\u0345\n\na\n\nb","complete":false,"budget_honored":false,"budget":2,"returned_bytes":4,"spans":[[3,4],[1,3],[0,1],[4,6],[6,7]],"group_order":[1,0,2]}}},
{"body":"a\n\n\u0345\n\nb","query":"","budget":2,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"a\n\n","continuation":"\u0345\n\nb","full_text":"a\n\n\u0345\n\nb","complete":false,"budget_honored":false,"budget":2,"returned_bytes":3,"spans":[[0,1],[1,3],[3,4],[4,6],[6,7]],"group_order":[0,1,2]},"ordered":{"version":"dependency-groups-utf8-v1","text":"a\n\n","continuation":"\u0345\n\nb","full_text":"a\n\n\u0345\n\nb","complete":false,"budget_honored":false,"budget":2,"returned_bytes":3,"spans":[[0,1],[1,3],[3,4],[4,6],[6,7]],"group_order":[0,1,2]}}},
{"body":"- \n\n- x\n\nz","query":"z","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"- \n\n- x\n\n","continuation":"z","full_text":"- \n\n- x\n\nz","complete":false,"budget_honored":false,"budget":3,"returned_bytes":9,"spans":[[0,7],[7,9],[9,10]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"z\n\n","continuation":"- \n\n- x","full_text":"z\n\n- \n\n- x","complete":false,"budget_honored":true,"budget":3,"returned_bytes":3,"spans":[[9,10],[7,9],[0,7]],"group_order":[1,0]}}},
{"body":"- \n\n- x\n\nz","query":"","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"- \n\n- x\n\n","continuation":"z","full_text":"- \n\n- x\n\nz","complete":false,"budget_honored":false,"budget":3,"returned_bytes":9,"spans":[[0,7],[7,9],[9,10]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"- \n\n- x\n\n","continuation":"z","full_text":"- \n\n- x\n\nz","complete":false,"budget_honored":false,"budget":3,"returned_bytes":9,"spans":[[0,7],[7,9],[9,10]],"group_order":[0,1]}}},
{"body":"\u0661. \n\n\u0662. x\n\nz","query":"z","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"\u0661. \n\n\u0662. x\n\n","continuation":"z","full_text":"\u0661. \n\n\u0662. x\n\nz","complete":false,"budget_honored":false,"budget":3,"returned_bytes":13,"spans":[[0,9],[9,11],[11,12]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"z\n\n","continuation":"\u0661. \n\n\u0662. x","full_text":"z\n\n\u0661. \n\n\u0662. x","complete":false,"budget_honored":true,"budget":3,"returned_bytes":3,"spans":[[11,12],[9,11],[0,9]],"group_order":[1,0]}}},
{"body":"\u0661. \n\n\u0662. x\n\nz","query":"","budget":3,"expected":{"plain":{"version":"dependency-groups-utf8-v1","text":"\u0661. \n\n\u0662. x\n\n","continuation":"z","full_text":"\u0661. \n\n\u0662. x\n\nz","complete":false,"budget_honored":false,"budget":3,"returned_bytes":13,"spans":[[0,9],[9,11],[11,12]],"group_order":[0,1]},"ordered":{"version":"dependency-groups-utf8-v1","text":"\u0661. \n\n\u0662. x\n\n","continuation":"z","full_text":"\u0661. \n\n\u0662. x\n\nz","complete":false,"budget_honored":false,"budget":3,"returned_bytes":13,"spans":[[0,9],[9,11],[11,12]],"group_order":[0,1]}}}
]
"""#
}
