// ScannerTests.swift
// Part-2 conformance tests: scanners, digest, token estimation, trailer split.
//
// Test strategy:
//   1. Load scanner-vectors-v22.json (generated by Oracle/gen_scanner_vectors.py).
//   2. Load originals and enrichment_trailer from the JSONL beds (Vectors/).
//   3. For each of the 509 oracle rows verify:
//      a. sourceDigest(original)       == source_sha256
//      b. estimateTokens(original)     == original_tokens_est
//      c. splitEnrichment(p23)         == split_enrichment.(body, trailer)
//      d. For each of the 26 named patterns:
//         finditer(pattern:in:)        == matches[name]
//
// JSON format (scanner-vectors-v22.json):
//   root: { version, bed_order, pattern_names, rows: [...] }
//   row:  { bed, drawer_id, source_sha256, original_tokens_est,
//           split_enrichment: {body, trailer},
//           matches: { PATTERN_NAME: [{s,e,g:[full,cap1,...]}, ...] } }
//
// Match format: g[0] = full match text (Python m.group(0), skipped here),
//               g[1+] = capturing groups (Python m.groups()).
// MatchResult.groups stores only capturing groups, so we drop g[0].

import Testing
@testable import ContextDistillLib
import Foundation

// MARK: - Vector model

private struct ScannerVector {
    let drawerID: String
    let bed: String
    let sourceSHA256: String
    let originalTokensEst: Int
    let enrichmentTrailer: String          // from JSONL (absent in JSON)
    let trailerBody: String                // from split_enrichment.body in JSON
    let trailerTrailer: String             // from split_enrichment.trailer in JSON
    let original: String                   // from JSONL
    // name → [(start, end, capturing-groups)]  — g[0] (full match) already dropped
    let patternMatches: [String: [(Int, Int, [String?])]]
}

// MARK: - Vector loading

private func loadScannerVectors() -> [ScannerVector] {
    // ── Step 1: Load JSON skeleton (everything except original text). ──
    guard let url = Bundle.module.url(
        forResource: "scanner-vectors-v22",
        withExtension: "json",
        subdirectory: "Vectors"
    ) else {
        preconditionFailure("Missing scanner-vectors-v22.json in Vectors/")
    }
    let data: Data
    do { data = try Data(contentsOf: url) }
    catch { preconditionFailure("Cannot read scanner-vectors-v22.json: \(error)") }

    guard let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
          let rowsAny = root["rows"] as? [[String: Any]]
    else { preconditionFailure("Bad JSON structure in scanner-vectors-v22.json") }

    // ── Step 2: Load originals and enrichment_trailer from JSONL beds. ──
    // drawerID → (original, enrichment_trailer)
    var byDrawerID: [String: (orig: String, trailer: String)] = [:]
    for bed in ["debug7", "sample30", "locomo", "blind200"] {
        guard let bedURL = Bundle.module.url(
            forResource: "\(bed)-intent-span-v22",
            withExtension: "jsonl",
            subdirectory: "Vectors"
        ),
              let raw = try? String(contentsOf: bedURL, encoding: .utf8)
        else { continue }
        for line in raw.components(separatedBy: "\n") {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            guard !trimmed.isEmpty,
                  let d = trimmed.data(using: .utf8),
                  let obj = try? JSONSerialization.jsonObject(with: d) as? [String: Any],
                  let orig = obj["original"] as? String,
                  let drawer = obj["drawer_id"] as? String
            else { continue }
            let enrTrailer = (obj["enrichment_trailer"] as? String) ?? ""
            byDrawerID[drawer] = (orig: orig, trailer: enrTrailer)
        }
    }

    // ── Step 3: Parse each JSON row into a ScannerVector. ──
    return rowsAny.map { row in
        let drawerID   = (row["drawer_id"]           as? String) ?? "<unknown>"
        let bed        = (row["bed"]                 as? String) ?? "<unknown>"
        let sha256     = (row["source_sha256"]        as? String) ?? ""
        let tokEst     = (row["original_tokens_est"] as? Int)    ?? 0

        // split_enrichment is the oracle output for splitEnrichment(p23).
        let split      = row["split_enrichment"]     as? [String: Any]
        let splitBody  = (split?["body"]             as? String) ?? ""
        let splitTrailer = (split?["trailer"]        as? String) ?? ""

        // matches: { PATTERN_NAME: [{s,e,g:[full,cap1,cap2,...]}, ...] }
        let pm = (row["matches"] as? [String: Any]) ?? [:]
        var parsedMatches: [String: [(Int, Int, [String?])]] = [:]
        for (name, matchesAny) in pm {
            guard let matchArr = matchesAny as? [[String: Any]] else { continue }
            parsedMatches[name] = matchArr.compactMap { m -> (Int, Int, [String?])? in
                guard let s = m["s"] as? Int,
                      let e = m["e"] as? Int
                else { return nil }
                // g[0] = full match (Python m.group(0)) — skip; not in MatchResult.
                // g[1+] = capturing groups (Python m.groups()).
                let gAny = m["g"] as? [Any] ?? []
                let groups: [String?] = gAny.dropFirst().map { g -> String? in
                    if g is NSNull { return nil }
                    return g as? String
                }
                return (s, e, groups)
            }
        }

        let pair = byDrawerID[drawerID]
        return ScannerVector(
            drawerID: drawerID,
            bed: bed,
            sourceSHA256: sha256,
            originalTokensEst: tokEst,
            enrichmentTrailer: pair?.trailer ?? "",
            trailerBody: splitBody,
            trailerTrailer: splitTrailer,
            original: pair?.orig ?? "",
            patternMatches: parsedMatches
        )
    }
}

// MARK: - Scanner assertion helper

/// Asserts that `finditer(pattern:in:)` matches the expected decoded triples.
private func assertPatternMatches(
    _ patternName: String,
    scalars: [Unicode.Scalar],
    expected: [(Int, Int, [String?])],
    drawerID: String
) {
    let actual = finditer(pattern: patternName, in: scalars)

    #expect(
        actual.count == expected.count,
        "Pattern \(patternName) count mismatch for \(drawerID): expected \(expected.count), got \(actual.count)"
    )

    let limit = min(actual.count, expected.count)
    for idx in 0 ..< limit {
        let (es, ee, eg) = expected[idx]
        let am = actual[idx]
        let expStr = fmtMatch(start: es, end: ee, groups: eg)
        let actStr = fmtMatch(start: am.start, end: am.end, groups: am.groups)
        #expect(
            am.start == es && am.end == ee && am.groups == eg,
            "Pattern \(patternName) match[\(idx)] for \(drawerID): expected \(expStr), got \(actStr)"
        )
    }
}

/// Pretty-prints a match triple for failure messages.
private func fmtMatch(start: Int, end: Int, groups: [String?]) -> String {
    let gStr = groups.map { $0.map { "\"\($0)\"" } ?? "nil" }.joined(separator: ", ")
    return "[\(start), \(end), [\(gStr)]]"
}

// MARK: - Digest tests

@Test("sourceDigest matches source_sha256 — debug7 (7 rows)")
func digestConformance_debug7() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "debug7" }) {
        let actual = sourceDigest(v.original)
        #expect(actual == v.sourceSHA256,
                "SHA256 mismatch for \(v.drawerID): expected \(v.sourceSHA256), got \(actual)")
    }
}

@Test("sourceDigest matches source_sha256 — sample30 (30 rows)")
func digestConformance_sample30() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "sample30" }) {
        let actual = sourceDigest(v.original)
        #expect(actual == v.sourceSHA256,
                "SHA256 mismatch for \(v.drawerID)")
    }
}

@Test("sourceDigest matches source_sha256 — locomo (272 rows)")
func digestConformance_locomo() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "locomo" }) {
        let actual = sourceDigest(v.original)
        #expect(actual == v.sourceSHA256,
                "SHA256 mismatch for \(v.drawerID)")
    }
}

@Test("sourceDigest matches source_sha256 — blind200 (200 rows)")
func digestConformance_blind200() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "blind200" }) {
        let actual = sourceDigest(v.original)
        #expect(actual == v.sourceSHA256,
                "SHA256 mismatch for \(v.drawerID)")
    }
}

// MARK: - Token estimation tests

@Test("estimateTokens matches original_tokens_est — debug7")
func tokenEstConformance_debug7() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "debug7" }) {
        let actual = estimateTokens(v.original)
        #expect(actual == v.originalTokensEst,
                "Token mismatch for \(v.drawerID): expected \(v.originalTokensEst), got \(actual)")
    }
}

@Test("estimateTokens matches original_tokens_est — sample30")
func tokenEstConformance_sample30() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "sample30" }) {
        let actual = estimateTokens(v.original)
        #expect(actual == v.originalTokensEst,
                "Token mismatch for \(v.drawerID): expected \(v.originalTokensEst), got \(actual)")
    }
}

@Test("estimateTokens matches original_tokens_est — locomo")
func tokenEstConformance_locomo() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "locomo" }) {
        let actual = estimateTokens(v.original)
        #expect(actual == v.originalTokensEst,
                "Token mismatch for \(v.drawerID)")
    }
}

@Test("estimateTokens matches original_tokens_est — blind200")
func tokenEstConformance_blind200() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "blind200" }) {
        let actual = estimateTokens(v.original)
        #expect(actual == v.originalTokensEst,
                "Token mismatch for \(v.drawerID)")
    }
}

// MARK: - Trailer split tests

/// Reconstructs the p23 string (original + optional trailer) that splitEnrichment
/// expects, exactly as gen_scanner_vectors.py does:
///   combined = original + " " + enrichment_trailer   (if non-empty)
///   combined = original                               (if empty)
private func p23(v: ScannerVector) -> String {
    v.enrichmentTrailer.isEmpty ? v.original : v.original + " " + v.enrichmentTrailer
}

@Test("splitEnrichment matches split_enrichment — debug7")
func trailerSplitConformance_debug7() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "debug7" }) {
        let (body, trailer) = splitEnrichment(p23(v: v))
        #expect(body == v.trailerBody,
                "body mismatch for \(v.drawerID)")
        #expect(trailer == v.trailerTrailer,
                "trailer mismatch for \(v.drawerID)")
    }
}

@Test("splitEnrichment matches split_enrichment — sample30")
func trailerSplitConformance_sample30() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "sample30" }) {
        let (body, trailer) = splitEnrichment(p23(v: v))
        #expect(body == v.trailerBody,
                "body mismatch for \(v.drawerID)")
        #expect(trailer == v.trailerTrailer,
                "trailer mismatch for \(v.drawerID)")
    }
}

@Test("splitEnrichment matches split_enrichment — locomo")
func trailerSplitConformance_locomo() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "locomo" }) {
        let (body, trailer) = splitEnrichment(p23(v: v))
        #expect(body == v.trailerBody && trailer == v.trailerTrailer,
                "split mismatch for \(v.drawerID)")
    }
}

@Test("splitEnrichment matches split_enrichment — blind200")
func trailerSplitConformance_blind200() {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == "blind200" }) {
        let (body, trailer) = splitEnrichment(p23(v: v))
        #expect(body == v.trailerBody && trailer == v.trailerTrailer,
                "split mismatch for \(v.drawerID)")
    }
}

// MARK: - Scanner conformance tests (per-pattern, per-bed)

/// All 26 pattern names in declaration order (must match Scanners.swift dispatch).
private let allPatternNames: [String] = [
    "TRAILER_RE", "PIPE_SPLIT_RE", "INLINE_NUMBERED_RE", "LIST_MARKER_RE",
    "WORD_RE", "NUMBER_RE", "DATE_RE", "CAPITALIZED_RE",
    "GREETING_PREFIX_RE", "GREETING_ONLY_RE", "DIALOGUE_FILLER_ONLY_RE",
    "REVISION_MARKER_RE", "INITIAL_DRAFT_MARKER_RE", "OPERATIVE_RE",
    "TURN_FILLER_RE", "ASSISTANT_BOILERPLATE_RE", "EMBEDDED_USER_FACT_RE",
    "FENCE_OPEN_RE", "MARKDOWN_HEADING_RE", "BOLD_HEADING_RE",
    "FIELD_LINE_RE", "TABLE_SEPARATOR_RE", "DIAGRAM_RE",
    "POLARITY_ONLY_RE", "TRANSFORM_FOLLOWUP_RE", "QUANTITY_VALUE_RE",
]

/// Runs all 26 pattern scanners against all rows in one bed.
private func runScannerConformance(bed: String) {
    let vecs = loadScannerVectors()
    for v in vecs.filter({ $0.bed == bed }) {
        let scalars = Array(v.original.unicodeScalars)
        for name in allPatternNames {
            let expected = v.patternMatches[name] ?? []
            assertPatternMatches(name, scalars: scalars, expected: expected, drawerID: v.drawerID)
        }
    }
}

@Test("Scanner conformance — debug7 (7 rows × 26 patterns)")
func scannerConformance_debug7() {
    runScannerConformance(bed: "debug7")
}

@Test("Scanner conformance — sample30 (30 rows × 26 patterns)")
func scannerConformance_sample30() {
    runScannerConformance(bed: "sample30")
}

@Test("Scanner conformance — locomo (272 rows × 26 patterns)")
func scannerConformance_locomo() {
    runScannerConformance(bed: "locomo")
}

@Test("Scanner conformance — blind200 (200 rows × 26 patterns)")
func scannerConformance_blind200() {
    runScannerConformance(bed: "blind200")
}

// MARK: - Smoke tests for PythonText helpers

@Test("isPythonWhitespace covers the exact Python isspace() set")
func pythonWhitespaceCoverage() {
    // Use a helper to avoid Swift Testing macro UInt8 overflow on large scalar values.
    func ws(_ v: UInt32) -> Bool { isPythonWhitespace(Unicode.Scalar(v)!) }
    // ASCII whitespace
    #expect(ws(0x09))     // \t
    #expect(ws(0x0A))     // \n
    #expect(ws(0x0B))     // \v
    #expect(ws(0x0C))     // \f
    #expect(ws(0x0D))     // \r
    #expect(ws(0x20))     // SPACE
    #expect(ws(0x85))     // NEL
    #expect(ws(0xA0))     // NO-BREAK SPACE
    #expect(ws(0x3000))   // IDEOGRAPHIC SPACE
    // Non-whitespace
    #expect(!ws(0x21))    // !
    #expect(!ws(0x41))    // A
    #expect(!ws(0x1C))    // FILE SEPARATOR (not whitespace in Python)
}

@Test("pySplit matches Python str.split() semantics")
func pySplitBehaviour() {
    let text = "  hello   world  "
    let scalars = Array(text.unicodeScalars)
    let tokens = pySplit(scalars).map { $0.asString() }
    #expect(tokens == ["hello", "world"])

    let empty = pySplit([]).map { $0.asString() }
    #expect(empty.isEmpty)

    let noWs = Array("abc".unicodeScalars)
    #expect(pySplit(noWs).count == 1)
}

@Test("estimateTokens(empty) returns 0")
func estimateTokensEmpty() {
    #expect(estimateTokens("") == 0)
}

@Test("utf8ByteOffset converts code-point index to UTF-8 byte offset")
func utf8ByteOffsetConversion() {
    // "Aé" = A (1 byte) + é (U+00E9, 2 bytes)
    let scalars = Array("Aé".unicodeScalars)
    let off0 = utf8ByteOffset(forCodePoint: 0, in: scalars)
    let off1 = utf8ByteOffset(forCodePoint: 1, in: scalars)
    let off2 = utf8ByteOffset(forCodePoint: 2, in: scalars)
    #expect(off0 == 0)
    #expect(off1 == 1)
    #expect(off2 == 3)
}
