import Foundation

/// A unit of verbatim content stored in the MemPalace surface.
///
/// A drawer is what callers ingest and what the search pipeline
/// returns. The `content` field is preserved unchanged — no
/// truncation, no normalization — because the verbatim-first
/// pillar of MemPalace requires that retrieval surface exactly
/// what was filed.
///
/// Wing and room are metadata-only strings. They participate in
/// taxonomy queries (`listWings`, `listRooms`) by `SELECT DISTINCT`
/// at query time; there is no `wings` or `rooms` table. This
/// matches MemPalace's runtime behavior — wings emerge from the
/// data rather than being declared up front.
///
/// `embeddingModelID` is present from day one even though no
/// embeddings are generated in this mission. The modelID-tagging
/// rule (one of the architectural constraints of Loci Mode)
/// requires every drawer to carry the identifier of the embedder
/// that produced its vector, so that vectors generated by
/// different models can never be compared accidentally. The
/// column exists from Rev 1.0 to avoid a migration when LOCI-2
/// wires embedding generation in.
///
/// `tombstonedAt` and `removedByBatch` belong to the soft-delete
/// machinery added in Rev 2.0. They are present on the schema
/// from Rev 1.0 so the layout never needs to migrate; both are
/// nil on every drawer Bilby writes through this mission and
/// are not read by any query.
public struct Drawer: Equatable, Hashable, Codable, Sendable {

    /// Stable identifier supplied by the caller. Defaults to a
    /// fresh UUID string when omitted; callers ingesting
    /// previously-known content should supply a deterministic id
    /// (for example, derived from `sourceFile` + `chunkIndex`).
    public let id: String

    /// Lineage identifier shared across all versions of a single
    /// content lineage per spec § 5.10. Always present, never nil.
    /// When the caller omits this argument the substrate generates a
    /// fresh `UUID()` so each new drawer is its own lineage by
    /// default. Callers ingesting a revised version of an existing
    /// content lineage supply the prior drawer's `lineageID`,
    /// triggering the supersession cascade per § 6.2 / § 6.3.
    public let lineageID: UUID

    /// The content as filed. Verbatim, no transformation.
    public let content: String

    /// Top-level taxonomy bucket. Free-form string;
    /// `listWings` aggregates whatever values are present in the
    /// store rather than checking against a closed set.
    public let wing: String

    /// Sub-taxonomy bucket inside a wing. Free-form string,
    /// scoped under `wing` only by convention.
    public let room: String

    /// Optional path of the file this drawer was ingested from.
    /// The directory walker (LOCI-6) writes this; manually-added
    /// drawers leave it nil.
    public let sourceFile: String?

    /// Optional position of this drawer inside its source. Used
    /// by the directory walker to dedup re-ingest cycles —
    /// chunkIndex 0 of the same sourceFile replaces the prior
    /// chunk 0 rather than being added as a duplicate.
    public let chunkIndex: Int?

    /// Name of the agent or process that filed this drawer.
    public let addedBy: String

    /// When the drawer was added. Stored as TEXT ISO8601 in
    /// SQLite per the MOOTx01 fleet rule. This is the ingest clock —
    /// when the row entered the local store, monotonically increasing,
    /// the anchor for CRDT convergence and audit ordering. It does not
    /// change. The "when did we learn this" clock; contrast `eventTime`.
    public let filedAt: Date

    /// Event time: when the thing happened or was authored in the
    /// world. For streaming capture this equals `filedAt`. For bulk
    /// historical ingestion callers supply the original authorship
    /// date. The fingerprint's capture-week bucket (DrawerFingerprint
    /// § 3.4) and all temporal cognition primitives key off this
    /// field, not `filedAt`. Stored as TEXT ISO8601 like `filedAt`.
    public let eventTime: Date

    /// Identifier of the embedding model that produced (or will
    /// produce) the vector for this drawer. Present from Rev 1.0
    /// so the modelID-tagging contract is enforceable from day
    /// one; this mission does not generate embeddings, so
    /// callers supply a placeholder.
    public let embeddingModelID: String

    /// When this drawer was tombstoned, if it has been. Reserved
    /// for the Rev 2.0 soft-delete workflow; always nil at
    /// Rev 1.0.
    public let tombstonedAt: Date?

    /// Batch identifier used for receipt-based rollback of a
    /// tombstone. Reserved for the Rev 2.0 soft-delete workflow;
    /// always nil at Rev 1.0.
    public let removedByBatch: String?

    /// Provenance bitmap encoding source_type, confirmation state,
    /// confidence, channel, and sensitivity per
    /// Q1_DECISION_PROVENANCE_BITMAP.md. See computed accessors in
    /// the extension below for type-safe access to each axis.
    /// Defaults to `0` (all axes unknown / sensitivity normal) when
    /// the caller does not declare provenance at capture time. The
    /// underlying SQLite column is `INTEGER NOT NULL DEFAULT 0`,
    /// matching this default end-to-end.
    public let provenance: Int64

    /// Adjective bitmap encoding state, sensitivity, exportability,
    /// and trust per spec § 5.5. See `Adjectives.swift` for the four
    /// enums and the computed accessors (`state`,
    /// `adjectiveSensitivity`, `exportability`, `trust`) plus the
    /// state-cluster predicates (`isCurrentlyBelieved`,
    /// `isKnewPast`, `isTerminal`) per § 6.1. Defaults to `0`
    /// (state `.active`, sensitivity `.normal`, exportability
    /// `.private_`, trust `.verbatim`). Persisted in SQLite via the
    /// `adjectiveBitmap` column shipped in LOCI_V035_01B.
    public let adjectiveBitmap: Int64

    /// Operational bitmap encoding capture channel, content kind,
    /// feature flags, and the state-extension flag per spec § 5.6.
    /// See `DrawerOperational.swift` for the two enums
    /// (`CaptureChannel`, `ContentKind`), the `DrawerFeatureFlags`
    /// OptionSet, and the computed accessors (`captureChannel`,
    /// `contentKind`, `featureFlags`, `hasFeatureFlag`,
    /// `stateExtensionActive`). Defaults to `0` (channel `.typed`,
    /// kind `.prose`, no feature flags, state-extension inactive).
    /// Persisted in SQLite via the `operationalBitmap` column
    /// shipped in LOCI_V035_02B.
    public let operationalBitmap: Int64

    /// Depth-axis classification code locating this drawer in the
    /// universal lattice per spec § 5.8 and invariant I-5 ("Every
    /// drawer carries a lattice anchor"). This is the storage-layer
    /// field: it is named `udcCode` for historical reasons (UDC was
    /// the originally specified scheme) but in the shipped system it
    /// carries an MDCC (MOOT Decimal Classification) code — MDCC is
    /// the live reference scheme. The MDCC-scheme value as produced
    /// by the reasoning layer is EideticLib/NeuronKit's separate
    /// `LatticeAnchorInference.mdccCode`; both are `String`, so the
    /// compiler does not police feeding one into the other. See
    /// § 5.8 "Two schemes, two field names" for the coexistence and
    /// the deferred storage-field rename. Empty string means "no
    /// anchor declared" — the no-anchor sentinel is empty rather
    /// than nil so the SQLite column can be `NOT NULL DEFAULT ''`,
    /// which keeps the migration path mechanical (every pre-04 row
    /// backfills trivially with the default). Persistence shipped in
    /// mission LOCI_V035_04; later missions add validation against the
    /// estate's `zoom_window` and the `lattice_citation` edition.
    public let udcCode: String

    /// Optional UDC facet expression refining `udcCode` per UDC's
    /// faceted syntax (e.g., `(03)=20` for "English-language
    /// reference work"). Nil means "no facet expression" —
    /// callers without faceted content store nil rather than the
    /// empty string so the SQLite column distinguishes "no facets
    /// recorded" from "facet expression intentionally blank."
    public let udcFacets: String?

    /// Primary Wikidata Q-ID anchoring this drawer to a stable
    /// concept identifier (e.g., `Q11351` for "organic chemistry").
    /// The Q-ID axis is the "what is this about" complement to
    /// `udcCode`'s "where in knowledge space." Nil means "no
    /// concept anchor declared."
    public let wikidataQID: String?

    /// Comma-separated secondary Wikidata Q-IDs for drawers whose
    /// content spans multiple concepts. Stored as a single TEXT
    /// column rather than a join table because the lattice anchor
    /// is read in every retrieval path and avoiding the join keeps
    /// the hot path single-row. Nil means "no secondary anchors";
    /// the format is the comma-separated Q-ID list with no
    /// internal whitespace (e.g., `Q41487,Q170978`).
    public let wikidataQidsSecondary: String?

    /// Designated initializer.
    public init(
        id: String = UUID().uuidString,
        content: String,
        wing: String,
        room: String,
        sourceFile: String? = nil,
        chunkIndex: Int? = nil,
        addedBy: String,
        filedAt: Date,
        // nil means "same as ingest time" — the streaming-capture
        // semantic. Swift cannot express `eventTime: Date = filedAt`
        // (a default may not reference another parameter), so the
        // sentinel is resolved to `filedAt` in the body below.
        eventTime: Date? = nil,
        embeddingModelID: String,
        tombstonedAt: Date? = nil,
        removedByBatch: String? = nil,
        provenance: Int64 = 0,
        adjectiveBitmap: Int64 = 0,
        operationalBitmap: Int64 = 0,
        lineageID: UUID = UUID(),
        udcCode: String = "",
        udcFacets: String? = nil,
        wikidataQID: String? = nil,
        wikidataQidsSecondary: String? = nil
    ) {
        self.id = id
        self.lineageID = lineageID
        self.content = content
        self.wing = wing
        self.room = room
        self.sourceFile = sourceFile
        self.chunkIndex = chunkIndex
        self.addedBy = addedBy
        self.filedAt = filedAt
        self.eventTime = eventTime ?? filedAt
        self.embeddingModelID = embeddingModelID
        self.tombstonedAt = tombstonedAt
        self.removedByBatch = removedByBatch
        self.provenance = provenance
        self.adjectiveBitmap = adjectiveBitmap
        self.operationalBitmap = operationalBitmap
        self.udcCode = udcCode
        self.udcFacets = udcFacets
        self.wikidataQID = wikidataQID
        self.wikidataQidsSecondary = wikidataQidsSecondary
    }
}
