#!/usr/bin/env bash
#
# distribution/publish-plugin.sh
#
# Publish the generated plugin tree (distribution/plugin/) to the public
# distribution repository codedaptive/mootx01-plugin. Run immediately after
# tagging a release, alongside homebrew's update-formula.sh.
#
# The tree is GENERATED in EE by moot-packager (--plugin-repo) and synced to
# CE as a SHARED artifact. Never edit files here by hand — fix the canonical
# source in EE and regenerate.
#
# Usage:
#   distribution/publish-plugin.sh            # publish, tag with plugin version
#   PLUGIN_REPO_SSH=git@github.com:... to override the remote
#
# Portability: bash 3.2 (macOS default) and GNU/Linux. No associative arrays,
# no sed -i.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CE_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
SRC="$CE_ROOT/distribution/plugin"  # generated tree (script lives outside it)
REMOTE="${PLUGIN_REPO_SSH:-git@github-codedaptive:codedaptive/mootx01-plugin.git}"

[ -f "$SRC/.claude-plugin/plugin.json" ] || {
  echo "error: $SRC does not look like the generated plugin tree" >&2; exit 1; }

# Version from the generated manifest — single source of truth.
VERSION="$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['version'])" \
  "$SRC/.claude-plugin/plugin.json")"
[ -n "$VERSION" ] || { echo "error: could not read version from plugin.json" >&2; exit 1; }

# Optional gate: strict-validate before publishing when the claude CLI is present.
if command -v claude >/dev/null 2>&1; then
  claude plugin validate --strict "$SRC" >/dev/null || {
    echo "error: claude plugin validate --strict failed — not publishing" >&2; exit 1; }
  echo "✓ strict validation passed"
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "cloning $REMOTE ..."
git clone -q "$REMOTE" "$WORK/repo"
cd "$WORK/repo"

# Replace the tree wholesale with the generated content (repo is fully generated;
# .git is preserved, everything else mirrors distribution/plugin).
find . -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
# Copy including dotfiles/dirs (.claude-plugin, .codex, .mcp.json, ...).
(cd "$SRC" && tar cf - .) | tar xf -

git add -A
if git diff --cached --quiet; then
  echo "✓ content already up to date (v$VERSION)"
else
  git commit -q -m "MOOTx01 plugin v$VERSION

Generated by moot-packager; published from mootx01-ce distribution/plugin.
Requires the mootx01 binary: brew install codedaptive/mootx01-ce/mootx01"
  git push -q origin HEAD
  echo "✓ pushed v$VERSION"
fi

# Tag the plugin release (idempotent: skip if the tag exists).
if ! git rev-parse -q --verify "refs/tags/v$VERSION" >/dev/null; then
  git tag "v$VERSION"
  git push -q origin "v$VERSION"
  echo "✓ published and tagged v$VERSION"
else
  echo "✓ published v$VERSION (tag already existed)"
fi
