// Int8VecConformanceTests.swift
//
// Cross-port conformance gate for the ratified int8 quantisation policy
// (ENCODER_RERANK_CONTRACT §4): Tests/Fixtures/encoder/int8_vectors.json,
// generated by gen_int8_vectors.py beside it and asserted by the Rust twin
// (rust/tests/int8_vec_conformance_tests.rs), so both ports are pinned to one
// file, not to each other.
//
// `q` and `scale` must match bit for bit: the inputs are decimals both ports
// decode to the same float32, so a byte difference is a rounding-mode, clamp,
// or divisor bug (half-to-even, ÷128, asymmetric range). `dot_query` must
// agree within 1e-5.

import Testing
import Foundation
import SubstrateKernel
@testable import SynapseKit

private struct Int8Fixture: Decodable {
    struct Vector: Decodable {
        let v: [Float]
        let q: [Int8]
        let scale: Float
        let dot_query: Float
    }
    struct Group: Decodable {
        let dim: Int
        let query: [Float]
        let vectors: [Vector]
    }
    struct Edge: Decodable {
        let note: String
        let query: [Float]
        let v: [Float]
        let q: [Int8]
        let scale: Float
        let dot_query: Float
    }
    let groups: [Group]
    let edge: [Edge]

    /// Tests/SynapseKitTests/<this file> → Tests/Fixtures/encoder/int8_vectors.json.
    static func load() throws -> Int8Fixture {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/encoder/int8_vectors.json")
        return try JSONDecoder().decode(Int8Fixture.self, from: Data(contentsOf: url))
    }
}

@Suite("Int8Vec conformance")
struct Int8VecConformanceTests {

    @Test("every fixture vector quantises bit-exactly and scores within 1e-5")
    func fixtureGroups() throws {
        let fixture = try Int8Fixture.load()
        #expect(fixture.groups.map(\.dim) == [8, 384, 768])
        for group in fixture.groups {
            #expect(group.vectors.count == 20)
            for (n, entry) in group.vectors.enumerated() {
                let (q, scale) = Int8Vec.quantize(entry.v)
                #expect(q == entry.q, "dim \(group.dim) vector \(n): q mismatch")
                #expect(scale.bitPattern == entry.scale.bitPattern,
                        "dim \(group.dim) vector \(n): scale \(scale) vs \(entry.scale)")
                let dot = Int8Vec.dotQuery(group.query, q: q, scale: scale)
                #expect(abs(dot - entry.dot_query) <= 1e-5,
                        "dim \(group.dim) vector \(n): dot \(dot) vs \(entry.dot_query)")
            }
        }
    }

    @Test("edge vectors: zero, one-hot, negative one-hot, exact .5 ties")
    func fixtureEdges() throws {
        let fixture = try Int8Fixture.load()
        #expect(fixture.edge.count == 4)
        for edge in fixture.edge {
            let (q, scale) = Int8Vec.quantize(edge.v)
            #expect(q == edge.q, "\(edge.note)")
            #expect(scale.bitPattern == edge.scale.bitPattern, "\(edge.note)")
            let dot = Int8Vec.dotQuery(edge.query, q: q, scale: scale)
            #expect(abs(dot - edge.dot_query) <= 1e-5, "\(edge.note)")
        }
    }
}
