//! Scanner conformance tests for CDL-01 Part 2 (Rust port).
//!
//! Loads scanner-vectors-v22.json (generated by gen_scanner_vectors.py)
//! and verifies every hand-written Rust scanner against the Python oracle
//! output for all 509 rows.
//!
//! Also verifies:
//!   - `source_digest` matches each row's `source_sha256`
//!   - `estimate_tokens` matches each row's `original_tokens_est`
//!   - `split_enrichment` matches each row's `split_enrichment` result

use context_distill_lib::{
    digest::{estimate_tokens, source_digest, split_enrichment},
    scanners::{scan_by_name, ScannerMatch},
};
use serde_json::Value;
use std::path::PathBuf;

// ---------------------------------------------------------------------------
// Vector loading
// ---------------------------------------------------------------------------

fn load_scanner_vectors() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../Tests/ContextDistillLibTests/Vectors/scanner-vectors-v22.json");
    let content = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Cannot read scanner-vectors-v22.json: {}", e));
    serde_json::from_str(&content).expect("scanner-vectors-v22.json is not valid JSON")
}

// ---------------------------------------------------------------------------
// Helper: convert oracle JSON match record to (start, end, groups)
// ---------------------------------------------------------------------------

fn oracle_match(m: &Value) -> (usize, usize, Vec<Option<String>>) {
    let s = m["s"].as_u64().unwrap() as usize;
    let e = m["e"].as_u64().unwrap() as usize;
    let g_arr = m["g"].as_array().unwrap();
    let groups: Vec<Option<String>> = g_arr
        .iter()
        .map(|v| if v.is_null() { None } else { Some(v.as_str().unwrap().to_string()) })
        .collect();
    (s, e, groups)
}

// ---------------------------------------------------------------------------
// Core assertion: Rust scanner matches oracle for one pattern on one row
// ---------------------------------------------------------------------------

fn assert_scanner_matches(
    pattern_name: &str,
    original: &str,
    oracle_matches: &[Value],
    row_idx: usize,
    bed: &str,
    drawer_id: &str,
) {
    let rust_matches = scan_by_name(pattern_name, original)
        .unwrap_or_else(|| panic!("Unknown pattern: {}", pattern_name));

    let expected_count = oracle_matches.len();
    let actual_count = rust_matches.len();
    assert_eq!(
        actual_count, expected_count,
        "Pattern {} row #{} bed={} drawer_id={}: \
         expected {} matches, got {}\n\
         First oracle match: {:?}\n\
         First Rust match: {:?}",
        pattern_name, row_idx, bed, drawer_id, expected_count, actual_count,
        oracle_matches.first(),
        rust_matches.first(),
    );

    for (i, (oracle, rust)) in oracle_matches.iter().zip(rust_matches.iter()).enumerate() {
        let (exp_s, exp_e, exp_g) = oracle_match(oracle);
        assert_eq!(
            rust.start_cp, exp_s,
            "Pattern {} row #{} bed={} drawer_id={} match #{}: \
             start_cp expected {}, got {}",
            pattern_name, row_idx, bed, drawer_id, i, exp_s, rust.start_cp
        );
        assert_eq!(
            rust.end_cp, exp_e,
            "Pattern {} row #{} bed={} drawer_id={} match #{}: \
             end_cp expected {}, got {}",
            pattern_name, row_idx, bed, drawer_id, i, exp_e, rust.end_cp
        );
        assert_eq!(
            rust.groups.len(), exp_g.len(),
            "Pattern {} row #{} bed={} drawer_id={} match #{}: \
             groups.len() expected {}, got {}",
            pattern_name, row_idx, bed, drawer_id, i, exp_g.len(), rust.groups.len()
        );
        for (gi, (exp, act)) in exp_g.iter().zip(rust.groups.iter()).enumerate() {
            assert_eq!(
                act, exp,
                "Pattern {} row #{} bed={} drawer_id={} match #{} group[{}]: \
                 expected {:?}, got {:?}",
                pattern_name, row_idx, bed, drawer_id, i, gi, exp, act
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn test_source_digest_all_rows() {
    let vecs = load_scanner_vectors();
    let rows = vecs["rows"].as_array().unwrap();

    for (idx, row) in rows.iter().enumerate() {
        let original = row["original"].as_str().unwrap_or_else(|| {
            // Original may not be stored separately; get from bed JSONL.
            // Actually gen_scanner_vectors.py doesn't store original in the
            // vector JSON.  We skip this check here and validate via the
            // separate digest fields.
            ""
        });
        // The vector file does not re-embed the original text (too large).
        // source_digest is validated by the generation script matching
        // source_sha256 from the JSONL.  We verify the function compiles
        // and produces the right length.
        let digest = source_digest("hello");
        assert_eq!(digest.len(), 64, "row {}: source_digest output must be 64 hex chars", idx);
        let _ = original; // satisfied by length check above
        break; // one structural check is sufficient; actual values checked in test_digest_fields
    }
}

#[test]
fn test_digest_fields_via_bed_jsonl() {
    // Load each JSONL bed and cross-check source_digest and estimate_tokens
    // against the stored oracle values in the JSONL rows.
    let beds = ["debug7", "sample30", "locomo", "blind200"];
    let base = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../Tests/ContextDistillLibTests/Vectors");

    for bed in &beds {
        let path = base.join(format!("{}-intent-span-v22.jsonl", bed));
        let content = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));
        for (i, line) in content.lines().filter(|l| !l.trim().is_empty()).enumerate() {
            let row: Value = serde_json::from_str(line)
                .unwrap_or_else(|e| panic!("bed={} row={} bad JSON: {}", bed, i, e));
            let original = row["original"].as_str().unwrap();
            let drawer_id = row["drawer_id"].as_str().unwrap_or("?");

            // source_digest check
            let expected_sha = row["source_sha256"].as_str().unwrap();
            let got_sha = source_digest(original);
            assert_eq!(
                got_sha, expected_sha,
                "source_digest mismatch bed={} row={} drawer_id={}",
                bed, i, drawer_id
            );

            // estimate_tokens check
            let expected_tok = row["metrics"]["original_tokens_est"].as_u64().unwrap();
            let got_tok = estimate_tokens(original);
            assert_eq!(
                got_tok, expected_tok,
                "estimate_tokens mismatch bed={} row={} drawer_id={}",
                bed, i, drawer_id
            );

            // split_enrichment check
            let enrichment_trailer = row.get("enrichment_trailer")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let combined = if enrichment_trailer.is_empty() {
                original.to_string()
            } else {
                format!("{} {}", original, enrichment_trailer)
            };
            // Load expected from scanner vector file (not inline here;
            // the split_enrichment values are in scanner-vectors-v22.json).
            // We just verify it doesn't panic.
            let (_body, _trailer) = split_enrichment(&combined);
        }
    }
}

#[test]
fn test_split_enrichment_oracle() {
    // Verify split_enrichment against the oracle values in scanner-vectors-v22.json.
    let vecs = load_scanner_vectors();
    let rows = vecs["rows"].as_array().unwrap();
    let beds = ["debug7", "sample30", "locomo", "blind200"];
    let base = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../Tests/ContextDistillLibTests/Vectors");

    // Load all JSONL rows in order (same order as scanner vectors)
    let mut jsonl_rows: Vec<(String, Value)> = Vec::new();
    for bed in &beds {
        let path = base.join(format!("{}-intent-span-v22.jsonl", bed));
        let content = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));
        for line in content.lines().filter(|l| !l.trim().is_empty()) {
            let row: Value = serde_json::from_str(line).expect("valid JSON");
            jsonl_rows.push((bed.to_string(), row));
        }
    }

    assert_eq!(rows.len(), jsonl_rows.len(), "row count mismatch between vector file and JSONL");

    for (idx, (vec_row, (bed, jsonl_row))) in rows.iter().zip(jsonl_rows.iter()).enumerate() {
        let original = jsonl_row["original"].as_str().unwrap();
        let enrichment_trailer = jsonl_row.get("enrichment_trailer")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let combined = if enrichment_trailer.is_empty() {
            original.to_string()
        } else {
            format!("{} {}", original, enrichment_trailer)
        };

        let (body, trailer) = split_enrichment(&combined);

        let exp_body = vec_row["split_enrichment"]["body"].as_str().unwrap();
        let exp_trailer = vec_row["split_enrichment"]["trailer"].as_str().unwrap();
        let drawer_id = vec_row["drawer_id"].as_str().unwrap_or("?");

        assert_eq!(
            body, exp_body,
            "split_enrichment body mismatch bed={} row={} drawer_id={}",
            bed, idx, drawer_id
        );
        assert_eq!(
            trailer, exp_trailer,
            "split_enrichment trailer mismatch bed={} row={} drawer_id={}",
            bed, idx, drawer_id
        );
    }
}

#[test]
fn test_scanner_conformance_all_patterns() {
    let vecs = load_scanner_vectors();
    let rows = vecs["rows"].as_array().unwrap();
    let pattern_names = vecs["pattern_names"].as_array().unwrap();

    // Load all JSONL originals in the same order as scanner vectors.
    let beds = ["debug7", "sample30", "locomo", "blind200"];
    let base = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../Tests/ContextDistillLibTests/Vectors");
    let mut originals: Vec<(String, String, String)> = Vec::new(); // (bed, drawer_id, original)
    for bed in &beds {
        let path = base.join(format!("{}-intent-span-v22.jsonl", bed));
        let content = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));
        for line in content.lines().filter(|l| !l.trim().is_empty()) {
            let row: Value = serde_json::from_str(line).expect("valid JSON");
            let drawer_id = row["drawer_id"].as_str().unwrap_or("?").to_string();
            let original = row["original"].as_str().unwrap().to_string();
            originals.push((bed.to_string(), drawer_id, original));
        }
    }
    assert_eq!(rows.len(), originals.len(), "row count mismatch");

    for (idx, (vec_row, (bed, drawer_id, original))) in
        rows.iter().zip(originals.iter()).enumerate()
    {
        let matches_obj = &vec_row["matches"];
        for name_val in pattern_names.iter() {
            let name = name_val.as_str().unwrap();
            let oracle_matches = matches_obj[name].as_array().unwrap();
            assert_scanner_matches(name, original, oracle_matches, idx, bed, drawer_id);
        }
    }
}
