#!/usr/bin/env python3
"""
generate_synthetic_wikidata_subset.py

Generates a SYNTHETIC Wikidata subset for EideticLib v0.1.0
development. Used because the live Wikidata Query Service is
under an aggressive temporary rate limit (1 req / min) that
makes assembly from the real source infeasible right now.

The output is structurally identical to what the real assembly
script will produce (same schema, same field shapes, same
LinguisticPipelineMode semantics) so the resolver code can be
built and tested against it. When WDQS recovers, the real
assembly script writes over WikidataSubset.json and nothing
else changes.

Q-IDs use the Q900000+ range, which Wikidata reserves for
placeholder and testing purposes. Labels and aliases are
derived from the UDC schedule's gazetteer terms so the
resolver tests can verify real lookup behavior even though the
Q-IDs themselves are not canonical.
"""

import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
UDC_SCHEDULE = (
    REPO_ROOT
    / "EideticLib"
    / "Sources"
    / "EideticLib"
    / "Resources"
    / "UDCSchedule.json"
)
OUTPUT_PATH = (
    REPO_ROOT
    / "EideticLib"
    / "Sources"
    / "EideticLib"
    / "Resources"
    / "WikidataSubset.json"
)


def synthetic_qid(seed: int) -> str:
    """Generate a synthetic Q-ID in the placeholder range.
    Wikidata reserves Q900000+ for testing and development;
    no real entity uses these."""
    return f"Q{900000 + seed}"


def assemble() -> dict:
    schedule = json.loads(UDC_SCHEDULE.read_text())
    entries: list[dict] = []
    qid_counter = 0

    # Section A: one synthetic anchor per UDC code with
    # gazetteer terms. The first gazetteer term becomes the
    # primary label; remaining terms become aliases. This
    # guarantees the resolver finds a match for any token that
    # hits the UDC classifier.
    for code_entry in schedule["codes"]:
        terms = code_entry.get("gazetteer_terms", [])
        if not terms:
            continue
        primary_label = terms[0].lower()
        aliases = [t.lower() for t in terms[1:]]

        entries.append({
            "qid": synthetic_qid(qid_counter),
            "label": primary_label,
            "aliases": aliases,
            "udc_hint": code_entry["code"],
            "source_section": "udc_anchor_synthetic",
        })
        qid_counter += 1

    return {
        "schema_version": "1",
        "data_version": "0.1.0-synthetic",
        "source_notes": (
            "SYNTHETIC DATA. Generated by "
            "EideticLib/tools/generate_synthetic_wikidata_subset.py "
            "while the live Wikidata Query Service is under an "
            "aggressive temporary rate limit (HTTP 429, 1 req per "
            "minute). Q-IDs are in the Q900000+ placeholder range "
            "and do NOT correspond to real Wikidata entities. "
            "Labels and aliases are derived from the UDC "
            "schedule's gazetteer terms so the resolver code "
            "exercises real lookup paths. Replace by running "
            "tools/assemble_wikidata_subset.py against the live "
            "WDQS endpoint when rate limiting recovers."
        ),
        "license_note": (
            "Synthetic placeholder data, no copyright. The "
            "structure matches Wikidata's CC0 dedication so the "
            "real-data replacement is a drop-in."
        ),
        "entries": entries,
    }


def main() -> int:
    subset = assemble()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        json.dumps(subset, indent=2, ensure_ascii=False) + "\n"
    )
    print(
        f"Wrote {OUTPUT_PATH} ({len(subset['entries'])} synthetic entries)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
